### ISSUE TITLE
Please log what audio input device Mycroft is using

### ISSUE THREAD

**Issue by singpolyma** [MycroftAI/mycroft-core#1030]
I've done some tweaking to the sound setup on my Mark 1 so that I can use HDMI output. Mycroft eas working with this, but just now is unresponsive and using the "test" option from the head-button menu plays "test 1,2,3" over HDMI so I think Mycroft may be listening on the wrong audio input. I've tried changing the device_index setting, but no luck so far. Hard to debug when the logs say nothing about what sound device is in use :)

**Comment by MrGrymReaper** [comment]
I also think this would be a good idea. As knowing what sound device is in use as well as for what. Sound Input and the output channel. Helpful when debugging per device and/or general configuration issues.

Also if there's a hard to reach bug affecting the software due to the configuration, interacting with other factors.

Giving more information to debugging during setup configuration and also fixing software bugs.

**Comment by forslund** [comment]
Basic information has been added here https://github.com/MycroftAI/mycroft-core/blob/dev/mycroft/client/speech/listener.py#L235

And for more info the mycroft-audiotest tool can be run with the -l option.

Closing this for now.
