### ISSUE TITLE
Unable to uninstall MyCroft from Fedora

### ISSUE THREAD

**Issue by NullTheSecond** [MycroftAI/mycroft-core#1113]

**Comment by forslund** [comment]
Hi,

I'll do my best to help you.

Could you provide some more info? Which install method did you use? Some package, github install or some other method?

**Comment by NullTheSecond** [comment]
I installed via GitHub install.

**Comment by el-tocino** [comment]
Going to need a few more details than that.  What step were you last able to complete successfully? (presuming you're using these instructions: https://docs.mycroft.ai/development/installation/git.clone.install ) What error did you get or what were you not able to do?

**Comment by NullTheSecond** [comment]
I installed via './dev_setup.sh'. What I can't do, is to uninstall, though.
I have only a few MB of data left, so I've been trying to remove it without
leaving stuff behind.

**Comment by forslund** [comment]
Things to remove:
- The mycroft-core directory
- The virtualenv: `~/.virtualenvs/mycroft`

The question is which packages you can remove since it depends on which packages you had installed before running the script. All the development packages should be ok, fann-devel, glib2-devel, openssl-devel, libicu-devel etc.

**Comment by forslund** [comment]
Hi, since there been no updates on this since September I assume this has resolved itself. I'm closing the issue but feel free to reopen it if this is still a problem.
