### ISSUE TITLE
Too many issues

### ISSUE THREAD

**Issue by Jack0da** [MycroftAI/mycroft-core#1116]
People, give the guys a chance!

**Comment by tjoen** [comment]
That's because there are many issues. If you want better software, report bugs and issues.

All these guys probably know we really appreciate their effords, but if stuff is suddenly broken because of updates, like custom wakeup words, please report it.

Because that is exactly what this site is for, making better software, together.

**Comment by forslund** [comment]
Thanks for the support @Jack0da!

However @tjoen is right, the issues and bug reports are helping us a lot! One does not need to write code to contribute to open source projects, bug reports and helping to test out the software are also great ways to contribute!

So a big thank you to you both!

Closing this issue to reduce the number of issues somewhat ;)
