### ISSUE TITLE
Change msm default skills without new package release

### ISSUE THREAD

**Issue by MatthewScholefield** [MycroftAI/mycroft-core#1136]
We should make a mechanism so after we release a new mycroft-core, we can edit the default skills to add more and msm will download the list rather than having them hard coded.

**Comment by el-tocino** [comment]
Have msm use a URL to find the default list instead.

**Comment by penrods** [comment]
Exactly, that is what we were thinking.  The Skill Management Team should be able to declare what skills are "default", stored in a file in the mycroft-skillls repo's root.  MSM will use that list instead of a hardcoded list.

The "default" declaration should be independent of mycroft-core build.  Of course users can override, but honestly I don't see any good reason they core team should have power over the Skill Repo.

**Comment by JarbasAI** [comment]
i changed my msm to read default skills list and skills dir from config file

won't make a PR because its super hacky (no so good with bash), but i basically made it read from a txt file like you suggest

the option to select skills install directory is also important to have imo

**Comment by forslund** [comment]
This was implemented in fef914f771f5a9c307a3dcbe19fc0e4d4d8234d2.
