### ISSUE TITLE
[META] Consider open sourcing websites?

### ISSUE THREAD

**Issue by Explouad** [MycroftAI/mycroft-core#12]
There seems to be a lot of issues that seem to be fixable if the websites went open side

**Comment by Explouad** [comment]
Went open source.* Is this possible? Just a suggestion.

**Comment by ryanleesipes** [comment]
@Explouad I agree! We are working to open source as many components as possible, with Cerberus we really have to decouple it from the rest of our company services in order to open it up. But as for docs and the community website (somebody registered mycroft.community writing this comment right now). Those certainly need to be opened up as soon as possible!

**Comment by ryanleesipes** [comment]
One site has been "opened", we are creating a Mycroft Community site: https://github.com/MycroftAI/mycroft-community-site - I would like to use a static site generator (like Jekyll or Pelican) for this site.

**Comment by ElCuboNegro** [comment]
I think they are talking about home.mycroft.ai and the backend
