### ISSUE TITLE
Mycroft isn't listening

### ISSUE THREAD

**Issue by mstormi** [MycroftAI/mycroft-core#1222]
I've observed this a couple of times: after I had issued a request, Mycroft first takes some time until it finally speaks out 'Please rephrase your request`. It does not accept any new input until it has finished speaking.

On another occasion, the first of the two messages below was printed on CLI, and Mycroft didn't accept any new speech input until the next message was seen (note the timestamps: exactly 30 seconds later).
No other log message was seen inbetween, and Mycroft had finished speaking.
I guess it's a bug with that recognizer_loop or the play command Mycroft uses for sound output.
It's always 30 seconds points between 'start' and 'stop', so that's likely some kind of timeout to get hit.

11:29:49.367 - SKILLS - DEBUG - {"type": "recognizer_loop:audio_output_start", "data": {}, "context": null}
11:30:19.431 - SKILLS - DEBUG - {"type": "recognizer_loop:audio_output_end", "data": {}, "context": null}

I run latest master branch on vanilla stretch Raspian + Pulseaudio installed on a Pi3 with a 4mic Respeaker mic array.

Now apart from the fact that the end of speech is not recognized, reading [issue #920](https://github.com/MycroftAI/mycroft-core/pull/920), I come to think that it is
intentional for Mycroft to NOT listen while it is still playing audio.
But it should already listen for the next command, shouldn't it ?
If you feel 'no' then at least make this a configurable behavior, please.

**Comment by forslund** [comment]
Hi @mstormi 
Mycroft currently mutest the mic while speaking. The mute is triggered by `recognizer_loop:audio_output_start` message and unmute is triggered by the `recognizer_loop:audio_output_end` message. So the weird thing is the long delay before sending audio_output_end...

Mycroft uses _paplay_ by default, on the picroft image (based on raspbian Jessie) that is overridden to _aplay_ since pulseaudio and the Pi audio hardware seems to not play nicely together.

See: https://github.com/MycroftAI/enclosure-picroft/blob/master/etc/mycroft/mycroft.conf

We have had some issues with Stretch, I don't know all the details but maybe @Mn0491 can fill in the blanks or offer additional support.

**Comment by Mn0491** [comment]
the issue we had with stretch was due to SSL certs issues. I also know that stretch has a different method of handling audio, not sure if that could be the case. @mstormi is this problem intermittent or always happening on stretch?

**Comment by mstormi** [comment]
Now that I switched to aplay as you recommended for my Pi3 (no change other than that,  I'm still on stretch), things are fine. So it was probably the Pi HW rather than Stretch.
Will do some more testing to confirm it's stable and will reopen this issue in case I find anything wrong.
Thanks for your support.

**Comment by forslund** [comment]
Great to hear it's working. It's good info for us to help other users!
