### ISSUE TITLE
Music skill

### ISSUE THREAD

**Issue by robocoder99** [MycroftAI/mycroft-core#123]
Mycroft most definitely needs a music playing skill if one has not been planned already. From talking to people this is one of the largest "needs" of an AI of this sort to have. Possible integrations with VLC, Spotify, etc.? There are a number of music apps and sadly they don't have a central API as far as I know so I am not certain how to go about that. I would certainly be willing to develop it if that problem were solved though.

**Comment by forslund** [comment]
I've been plaing around with these kinds of things for a while. My efforts can be seen at https://github.com/forslund/mycroft-media-skills

At the moment they use the mopidy media server for playing local music files and Spotify. Currently there's a lot of user input required to install but it works pretty good. Feel free to try it out, I would be grateful for any comments!

**Comment by robocoder99** [comment]
Yeah, a central media server with multiple integrations built-in is a smart way to do it. Maybe we could find some way to automate an "out of the box" install for this. I will look at your code, run it on my dev setup and get back to you.

**Comment by forslund** [comment]
Out of the box functionality would be nice and is the planned next step. Your contributions are welcome!

**Comment by grahamreeds** [comment]
My music library is on a NAS with Plex on it but any DLNA support would be
good.

Things to think about: "Mycroft, play Downward Spiral". Do you play the
album or the song or do you kick up an error as it is The Downward Spiral?

GR

**Comment by ChristopherRios7** [comment]
Hello all, 

Someone make this a pull request. 
I want this to be real skill. 

Regards,

Christopher

**Comment by forslund** [comment]
@grahamreeds, plex would be a nice addition. I'll look into adding plex as a media server in addition to mopidy. I'm looking into some DLNA support at the moment but as I'm only a happy hobbyist I will probably flounder for a while. If you have experience with this any pointers to resources or direct help are welcome.

Regarding the track vs album selection the current example skill is limited to albums due to some constraints in how generic a voice command can be (either the constraint is in mycroft or in my understanding of mycroft). This may change in the future.

**Comment by forslund** [comment]
@ChristopherRios7 I had this up for a PR a while ago but closed it since I couldn't automate all the installation steps. Someone (@clusterfudge maybe) suggested that it might be a good idea to have these skills in a separate container.

The skill-container approach should at least give people a chance to try the skill and provide feedback until the skill is in good enough shape to be considered to be included in mycroft-core or until someone makes a better solution.

**Comment by ChristopherRios7** [comment]
@forslund I agree with you about containerizing the skills, much like Snappy or Flatpack Packages. We as a team need to set guidelines for this. @clusterfudge - Let's work together on this. Cerberus should hold all skills and send the containerized skill to individual units on a persons account.

**Comment by robocoder99** [comment]
What is the current plan for non-trivial dependency handling? I assume at some point skills will be handled almost like packages installing them either via commands or adding them to a config to be installed automatically. Will the containerization you are currently planning handle that? I.e. Libspotify is a dependency of this skill but it "non trivial" to install as it is not apt-get etc.

**Comment by aatchison** [comment]
I think that we are making skills progress in multiple directions here, all of which reside outside of the core code in https://github.com/MycroftAI/mycroft-skills.
