### ISSUE TITLE
Bad Mycroft documentation or Mycroft tool for installing manually skills

### ISSUE THREAD

**Issue by yannick56** [MycroftAI/mycroft-core#1252]
Hello,

At https://docs.mycroft.ai/development/cheatsheet/ubuntu , the documentation said to do:
"
4.1 Manually
Let's add spanish radio skill: "Mycroft, spanish news" using 2 commands:
cd /ops/mycroft/skills
git clone https://github.com/ChrisFernandez/skill-radio-rne.git
"

I try:
cd /home/user/mycroft-core/mycroft/skills
git clone https://github.com/ChrisFernandez/skill-radio-rne.git
I restart mycroft software
cd ..
./start-mycroft.sh all
./start-mycroft.sh cli
and in the cli, I write 
Hey Mycroft, radio from Spain 
but it does not work.

Then I remove  /home/user/mycroft-core/mycroft/skills/skill-radio-rne folder
and I did:
cd /home/user/mycroft-core/msm
./msm install https://github.com/ChrisFernandez/skill-radio-rne.git
cd ..
cd mycroft
./start-mycroft.sh all
./start-mycroft.sh cli
and in the cli, I write 
Hey Mycroft, radio from Spain 
and it works.
But I find no skill-radio-rne folder to translate the *.voc files ein an other language.
Where are these files ?

What's the problem with the manual installation ?

**Comment by KathyReid** [comment]
Thanks so much @yannick56 for reporting this problem with the documentation. The documentation on docs.mycroft.ai is very out of date and I'm currently doing a full rewrite of the documentation. That said, I *can* provide some guidance on what's happened here. 

In the first installation location given by docs.mycroft.ai, it is 
`/ops/mycroft/skills`

This is incorrect, and should be
`/opt/mycroft/skills`

When you did a `git clone https://github.com/ChrisFernandez/skill-radio-rne.git`
into 
`/home/user/mycroft-core/mycroft/skills`
this _did not_ install the Skill into `/opt/mycroft/skills`. 

When you did the `./msm install https://github.com/ChrisFernandez/skill-radio-rne.git`, this operation did a `git clone` into `/opt/mycroft/skills`, and that's why it worked. 

The Skill files should be in
`/opt/mycroft/skills/skill-radio-rne`

Please let me know how you go, 
Kind regards, 
Kathy

**Comment by forslund** [comment]
@KathyReid's updated documentation has been released so this should not be an issue any more. See https://mycroft.ai/documentation/msm/.

Closing this one, feel free to open new issues if you find more inaccuracies.
