### ISSUE TITLE
Listener Improvements

### ISSUE THREAD

**Issue by ryanleesipes** [MycroftAI/mycroft-core#128]
The listener is still quite difficult to trip in many cases (specifically on the unit). And does not feature enough feedback to ensure that the user knows what is going on at each stage.

I propose a redesign to ensure a better user experience. Mycroft HQ will put together a library of  1000 recordings by June 16 to run tests against. We should begin making adjustments to the listener (both UX and technically) in order to make for a better experience.

**Comment by Wolfgange3311999** [comment]
What were you thinking on feedback to the user? Perhaps a series of debug logs saying:
Wake word detected! Removing wake word from audio... [Mycroft's face changes]
Transcribing audio... [Another subtle change on Mycroft's display]
Transcription: Tell me a joke. Finding intent...
Intent found: JokeIntent. Deciding response...
[Mycroft begins to speak]

I was thinking, since pocket sphinx is so lightweight, it might be nice to run that every 0.5 seconds while reading audio in `mic.py`. This way the user can get feedback that Mycroft heard his name even before they start/finish saying the sentence.

**Comment by ryanleesipes** [comment]
Yes, that or we might end up developing two separate modes - call and response, and passive listening. I think the passive listening (that we currently use), doesn't seem responsive enough. However, maybe that is just a lack of feedback.

This is something we have considerable issues with when using the technology, and through the changes we've made - we either get too many false positives, or it doesn't trigger often enough.

**Comment by ryanleesipes** [comment]
Notes:

1.) Add tone for acknowledgement.
2.) Add ability to change between passive and call+ Response in config file
3.) "Hey Mycroft" for Call+Response.
