### ISSUE TITLE
sending email with own email server

### ISSUE THREAD

**Issue by JarbasAl** [MycroftAI/mycroft-core#1343]
the current send email method uses Mycroft's api, privacy conscious users would want to use their own email server

this would also allow to send email to other persons instead of only to self

i am currently using yagmail package for this, what would be the best way to integrate this into core?

proof of concept: https://github.com/JarbasAl/jarbas-core/blob/email/mycroft/api/__init__.py#L183

**Comment by MatthewScholefield** [comment]
The purpose of `send_email` is to make a hassle-free way for skills to communicate with the user via email. Because of this, I think we should make sure that the user doesn't need to give their email username and password for receiving anything.

For privacy conscious users, I think it would make sense to host their own email endpoint that is something like a flask script that uses `yagmail.SMTP`. What do you think?

**Comment by JarbasAI** [comment]
i think you shouldn't be able to read / send all our mails as a default ... 

i'm duplicating the home backend locally as that seems the best approach https://github.com/JarbasAl/personal-mycroft-backend/

there are just too many privacy leaks, most recently metrics collecting all our transcriptions and the send email method

**Comment by JarbasAI** [comment]
why not do something like this by default

https://github.com/JarbasAl/skill-dictation

**Comment by NathanLKing** [comment]
Hi @JarbasAl 
Love your idea about this, did you get it to function in Mycroft?

Nathan

**Comment by forslund** [comment]
Closing Issue since we're archiving the repo
