### ISSUE TITLE
Feature request: Integrate IFTTT into the core

### ISSUE THREAD

**Issue by WSLUser** [MycroftAI/mycroft-core#1485]
#278  was incorrectly labeled as a "skill". In order to get IFTTT working, it will require altering the code inside the core to implement the IFTTT protocol and make use of the API at a minimum (there may be some smaller pieces that have to be added as well) and not just creating some "skill". Getting IFTTT integrated into the core could make skill creation go much faster and easier since there is much work already done in IFTTT world for add-ons to link otherwise incompatible devices/functions/services together. A starting point I see from searching IFTTT's Github [pages](https://github.com/IFTTT) would be their [ifttt-api-example](https://github.com/IFTTT/ifttt-api-example). I personally don't know enough to integrate it but happy to help in other ways (debug, pen-test, etc.)

**Comment by tsdorsey** [comment]
@KathyReid Could we get some feedback from the Mycroft Team on this? Would you be open to this or does it belong in a skill for now?

**Comment by DarthSpock** [comment]
I would upvote using blockchain-based ecosystem but not sure that would invalidate getting IFTTT support. Honestly, I just want to be able to use Mycroft with Alexa, Google, Siri, and whatever other AI is out there. Since this is the only open-source AI, using it to gain control of the propiertary ones would free users to purchase whichever devices they want and still be able to centrally control it via IFTTT. 

Also if you're considering considering blockchain, how deeply ingrained is [Deep Learning](https://www.technologyreview.com/s/513696/deep-learning/) into Mycroft core? Considering how current AI works now, this is an arena that will need improvement for some time for all current and future AI implementations (open-source or otherwise). We have a [Saudi Arabian citizen robot](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=0ahUKEwjS_7H4xeTaAhVqU98KHbz1A8UQtwIIKTAA&url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DE8Ox6H64yu8&usg=AOvVaw0W3xulEfuVV4dARLqNBWN7) already in existence.

**Comment by KathyReid** [comment]
So, two points here; 

* To the blockchain-based ecosystem point - we would need to work out how the ecosystem would interface with IFTTT, for instance would you need a Mycroft Token to use Mycroft with Alexa, Google or Siri? Or would those services consume Mycroft Token if they were passed a request from Mycroft? Still a lot to work through there. 

* To the Deep Learning point - deep learning and machine learning are not part of `mycroft-core`, however they're a part of several other software packages in the Mycroft ecosysem. The [Precise Wake Word engine](https://mycroft.ai/documentation/precise) uses a neural network to distinguish between what is a Wake Word and what is not, while the Mimic 2 Text to Speech layer uses a neural network to train voice models. 

I've been keeping a track of the Sophia citizen issue for a while - and what astounds me is that in a country like KSA, an AI is given citizenship, but its female population only just got the right to drive. We _also_ need to be deeply considering issues of diversity and inclusion alongside machine learning.

**Comment by DarthSpock** [comment]
I've never developed with IFTTT either but I'm thinking alittle of both. I wouldn't necessarily expect a skill developed specifically for Mycroft to work on say on an Echo Dot though that would be cool but I would expect to call the Echo Dot and all it's abilities from Mycroft via IFTTT. Actually the best comparison I can think of is the new Echo Dot Kids edition on [pre-order](https://www.amazon.com/dp/B077JFK5YH/ref=ods_surl?tag=googhydr-20&hvadid=266013371267&hvpos=1t1&hvnetw=g&hvrand=2703326173648796121&hvpone=&hvptwo=&hvqmt=e&hvdev=c&hvdvcmdl=&hvlocint=&hvlocphy=9061286&hvtargid=kwd-439600972494&ref=pd_sl_1icpeh95ic_e). You should check it out, pretty cool stuff for kids. There's a video that will kinda will show some of what Mycroft ought to be able to do via IFTTT.

**Comment by DarthSpock** [comment]
I think it depends on what each use-case is. Some people may want full blown IFTTT endpoint while others just want some compatibility. It would help if others pitched in some input on what they'd use IFTTT for.

**Comment by seriussoft** [comment]
I, personally and professionally, would love to be able to have the ability
to communicate to-and-fro my IFTTT compatible devices and my Picroft;
especially because baby of them may only open themselves to IFTTT. I've got
several finicky "wifi" light bulbs that are 1st/2nd gen and don't handle
updates well - too cost prohibitive to replace them all because they are
all over the house and individually the bulbs are expensive due to the
features set available. In general, IFTTT seems to be more compatible in
general with the slieu of "wifi-enabled" devices In familiar with: both
old/new and large/little.

Not to mention that the protocol itself is more widely known compared to
the alternatives amongst the lay but tech friendly masses looking to build
their own SMART-home little-by-little, so that means future devices are
often setup to take advantage of that when devs are forced to pick 1
standard/protocol to spend time + money + other-resources on in development.

I would love to be able to converse back and forth or setup a poll or to
full on client-host relationship between my devices such that the
Picroft/Mycroft could be the central hub: it would enable quicker
SMART-home implementation across all the devices instead of the causing a
huge fragmentation and complex backing whereby I have to create multiple
HUBs that communicate with the [My|Py]croft and my other IFTTT devices and
non IFTTT devices.

However, if forced to choose between getting my cake tomorrow (Client+Host
[ie Full] implementation in a year or 2) or eating it today (Client
implementation only to give us something to work with until the team has
time/resources for the full deal or some other implementation), I'd be
content with eating it today. Having something to work with sooner versus
waiting for a later date that might not even be what we expect/need today
means we don't have to sit idly by on our thumbs. It would open the door
for even more seemingly impossible/complex solutions that could make this
product desirable in even more homes across the world.

Thanks,
SeriousSoft

-----------------------------
Websites, Apps, and Consultation:
ASP.NET, C#, VB.NET, PHP, Ruby, and C++ Developer
http://Seriussoft.com
nathan.vanbuskirk@seriussoft.com

**Comment by forslund** [comment]
Closing Issue since we're archiving the repo
