### ISSUE TITLE
Pairing / Wifi connection not working Picroft

### ISSUE THREAD

**Issue by Flustered** [MycroftAI/mycroft-core#1553]
Hi, we have been struggling for hours with the same result...

Raspberry PI3
Fresh Mycroft inatall (tried twice)

The first time we go through the Wifi Setup Wizard, we click connect via phone/PC, connect to MYCROFT and then identify and enter real WIFI password.  But that's as far as we get...

Looking in the /etc/wpa_supplicant/wpa_supplicant.conf the wifi and password have been added (there are now 2 connections for MYCROFT is this right?)

But nothing else... I have registed, and all the support tells us to enter the registration code, but Mycroft is not giving us a code.  Just keeps repeating the but about connecting a PC or mobile device...

We are somehow stuck.  Who can help?

**Comment by Flustered** [comment]
Oh, yes...

Rebooted, and rebooted...  For an hour!!

**Comment by el-tocino** [comment]
if you can connect to the cli and type "whats my pairing code" does that do anything? Is a code showing in the logs?

**Comment by Flustered** [comment]
So, CTL-C to get to the command line and just type  "whats my pairing code" or is there a different commend line interface for Mycroft?

**Comment by aethyric-science** [comment]
If you are running the "Pi Day" release of Picroft, then this is an artifact of the upgrade from Python 2.7 to 3.4.

The new version of Python is established in a virtual environment, but the references to it are not included in the `auto_run.sh` script, and the Python code there and in the `messagebus_emit.py` script has not been updated to 3.4.

This is documented in [a message](https://community.mycroft.ai/t/import-error-no-module-named-mycroft-messagebus-client-ws/3817/6) from @forslund .

In order to accommodate this, we made the following adjustments in the home directory:

• Change lines 11 and 12 of the `auto_run.sh` script to read

```
source /opt/venvs/mycroft-core/bin/activate
mycroft_core_ver=$(python -c "import mycroft.version; print ('mycroft-core: '+mycroft.version.CORE_VERSION_STR)" | grep "core:")
```

• Add parentheses around the contents of the `print` functions on lines 12 – 16 and line 21 of `messagebus_emit.py` 

Note that other changes may be required for full functionality in other scripts, such as `say_command.py`, but the above sufficed to overcome the connection issues after re-booting for us.

**Comment by forslund** [comment]
I'm closing this issue since the Picroft image has been reworked and the wifi setup as well. If you feel this is incorrect feel free to reopen the issue.
