### ISSUE TITLE
Help me with python plz

### ISSUE THREAD

**Issue by PAKITRON5000** [MycroftAI/mycroft-core#1557]
Hello,
I'm from Spain so I apologize for my English,
this is my ptoblem:

PKT@DESKTOP-U3LLD30:~$ ls
instabot.py
PKT@DESKTOP-U3LLD30:~$ cd instabot.py
PKT@DESKTOP-U3LLD30:~/instabot.py$ ls
ISSUE_TEMPLATE.md  LICENSE  README.md  requirements.txt  src  trvpixe0.py
PKT@DESKTOP-U3LLD30:~/instabot.py$ python3 trvpixe0.py
python3: can't open file 'trvpixe0.py': [Errno 13] Permission denied
PKT@DESKTOP-U3LLD30:~/instabot.py$

-----------------------------------------------------------------------------------------

I've been looking for solutions for hours and I can not find anything, I've tried up to 2 different versions of Python
Can anybody help me please?
Thnx

**Comment by PAKITRON5000** [comment]
whenever I want to see something or execute some python I have to write python3 and the file, instead of just python, with only python tells me this
The program 'python' can be found in the following packages:
 * python-minimal
 * python3
Try: sudo apt install <selected package>

**Comment by forslund** [comment]
It sounds like a permission issue just like @KathyReid suggests. and you should check if you're allowed to read the files.

Are you running ubuntu in virtualbox/vmware or are you using the ubuntu layer in windows? 

The suggestion of packages is something you get in ubuntu if the software isn't installed. (in this case there's no python binary, which is a bit weird since there seem to be python3 installed). I suggest you try `sudo apt-get install python2.7` if you intend to run mycroft. we're soon switching to python3 but while we switch over python2.7 might be good to have installed anyway.

**Comment by PAKITRON5000** [comment]
nothing does not work, anyway I got closer with the cmd, now I have this error:
  File "C:\Python27\lib\json\decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

**Comment by forslund** [comment]
What is your goal here? running mycroft on windows?

**Comment by PAKITRON5000** [comment]
what I'm trying is that the instabot works, but I only get errors, this last error is thrown from cmd

  File "C:\Python27\lib\json\decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

@forslund

**Comment by forslund** [comment]
Ok closing this one.
