### ISSUE TITLE
extract number can not detect zero

### ISSUE THREAD

**Issue by JarbasAl** [MycroftAI/mycroft-core#1672]
extract_number should be refactored into returning None in the next major release, related #1670 

# issue demonstration

> hey mycroft, do arrays start at 0?

# code

    n = extract_number(utterance)
    if n:
        if n == 0:
            self.speak("yes")
        elif n == 1:
            self.speak("only in stupid languages")
        else:
           self.speak("nop")
    else:
            self.speak(utterance_remainder + " is not a number")

# expected output

>  yes

# actual output

> 0 is not a number

# solution

return None instead of False, that way we can check for 0

        if n is not None:

**Comment by forslund** [comment]
I agree that it makes more sense to return None when no number is found.

The zero seem to be a separate bug though. It should return 0 and not False (which makes it testable using

```python
if n is not False
```

**Comment by JarbasAI** [comment]
from PEP 8:

    Don't compare boolean values to True or False using ==

       Yes:   if greeting:

       No:    if greeting == True:

       Worse: if greeting is True:

Since you enforce pep8 on every PR....

**Comment by forslund** [comment]
This was fixed in #1673. Closing

**Comment by penrods** [comment]
I agree with your disagreement, Jarbas.  It is a guideline, but not an absolute.

The cases of zero, None and False are all similar but subtly different.  For extract_number() I intentionally made it fail zero and False similarly since most human questions don't get answered by zero very often.  ("Which item do you want" doesn't get answered with "number 0" or "the zeroth").

Anyway, this was ported directly from some PHP code that I had and they did it with False instead of None.  I agree that None is more Pythonic and we should move to it for the 18.08 API.  This probably won't break much, if any code.  But I'd rather keep to that policy of stable APIs that only have fully backwards compatible changes within a version.
