### ISSUE TITLE
Incidental findings from review of `dev_setup.sh`

### ISSUE THREAD

**Issue by KathyReid** [MycroftAI/mycroft-core#1714]
_Background_ Did a review of `dev_setup.sh` for #1712 and raised these questions during review, moving to new Issue to separate them out. 

### `dev_setup.sh`

1. In the `show_help()` function, recommend pointing the user to Chat or Forums if they have questions - this isn't a _technical_ thing per se, but it helps to grow the Dev Community

2. just a minor nit-pick, but I'd set the `opt_skipmimic` and `opt_allowroot` flags above `show_help()` and add comments around what they do. 

3. there is an `--allow-root` option, but the code does not allow for the similar `--skip-mimic` - for usability and predictable usage, recommend added `--skip-mimic` as an allowable option. 

4. In the code block that checks whether `--allow-root` is set, and exits if it is not, then I would add a log entry using `syslog` or similar to `mycroft-update.log`, as it makes sense to log this for troubleshooting. 

5. In the function `install_deps()` I'd be inclined to add commentary around which platform each package manager is usually associated with - this would likely help with troubleshooting in the future, particular for non-Debian flavours of Linux. 

6. I might be missing something, but why are we installing `python2` packages with some of the installers, for instance `pacman` for Manjaro? 

7. I think there is a typo in line 119 (of your commit, line 116 of previous commit) - reads `${blue} git python 2 python-setuptools ...`. I _think_ `python 2` should be `python2`. 

8. In the function `install_venv()`, how likely is it that the URL for `get-pip.py` will change in the future? Should it be abstracted into a var at the top of the bash script? 

9. On line 156 I think we should warn the user that building `mimic` can take upwards of an hour. 

10. Do we need to check that the `venv` installs successfully in `install_venv()` and log and exit if it doesn't? It doesn't seem like a common source of failures, but being thorough. 

11. Why do we force the version of `pip`? `pip` is up to about version 18, and I wonder if this causes any confusion? 

12. On line 234 do we need to set the execute bit for `start-venv.sh`? I'm not sure, so asking the question. 

13. why is `/var/log/mycroft` 777? Should it be 775 with `mycroft:mycroft` - again I'm not sure so more "kicking the tyres" / questioning. 

### main.py

* In function `check-dependencies()` we pipe `notify-send` to `/dev/null` - again should we syslog this to one of the logs for troubleshooting? 

END comments

**Comment by MatthewScholefield** [comment]
Note: I edited the description to use numbers so I could match them below

1. +1
2. +1
3. Agreed. I also think we should change it to `-bm, --build-mimic  Build mimic even if it has already been built` and remove the interactive prompt (because honestly, who rebuilds mimic anyways :P)
4. But `start-mycroft` is only used in github installs and called interactively by the user so I don't see the value of logging beyond printing to stdout
5. While it could be valuable, I would suggest we use git blame / history in a selection for this. It'd be more accurate and doesn't get out of date over time.
6. +1
7. +1 (Doesn't technically matter since it's telling the user the rough names of packages they should install on their own)
8. I don't think it's likely at all. I'd say as a general guideline we should wait for the first case to happen before extracting hardcoded values
9. +1
10. Same as the general guideline with 8. I'd say wait for it to happen at least once.
11. +2
12. We actually shouldn't need to set the executable flag for any script (so we should remove those lines). Git tracks the executable flag.
13. +1 Or even no chmod with chown

**Comment by fermulator** [comment]
RE (11); I too had this question and was going to submit an issue for it AND a PR to automatically upgrade pip.  Do we have historical evidence that "newer versions of pip" result in instability for mycroft installations? (it should not)

**Comment by forslund** [comment]
It has happend three times (if I recall correctly) when a new version of pip was released the setup broke. Once on git installs and two times on the packaging system for the Mark-1.

We also like to keep the git install synced to the one we use for packaging. We do update it occationally and it might be a good idea to update to 19.1 now since it's the last version supporting Python 3.4.

**Comment by krisgesling** [comment]
I know this is quite old, but there's a long list of potential improvements there and I don't want to presume that they've been fixed given no PR's have referenced this. 

If anyone is reading this for hacktoberfest, feel free to grab one or two items of this list, check them out and submit a PR :)
