### ISSUE TITLE
Centos 7 support

### ISSUE THREAD

**Issue by assasen11** [MycroftAI/mycroft-core#1836]
*I am trying to install Mycroft from the repo (what ever that newest version is)
*I am trying to install this on Centos 7 (which I know is not supported yet)

My basic process for understanding is listed as follows on a fresh minimal install.

1. sudo yum install epel-release
2. sudo yum update -y
3. sudo yum upgrade -y
4. sudo yum install nano wget git python-pip python-devel (This is not all of them)
5. sudo yum groupinstall 'development tools'

The main issue here is that dev_setup.sh will not work because it cannot use apt and it needs yum. However I was able to get pip to install the entire requirement.txt (with some work). I can go through the process again and correct every issue I ran into originally so we can get this working. However I am not very good with scripts so I would just need help fixing that so that it can easily be install on centos.

**Comment by forslund** [comment]
Hi, if you'd like to provide centos support you could probably use the package list for openSuse as guideline (also rpm based but uses *zypper* instead of yum if I've understood things correctly). You can see the section [here](https://github.com/MycroftAI/mycroft-core/blob/dev/dev_setup.sh#L112). It uses `found_exe` determine which packaging tool to use.

You should be able to add a section like this:
```sh
    elif found_exe yum ; then
    $SUDO yum install <FLAGS> <PACKAGES>
    ...
```

You seem to have a pretty good list of the required steps so it should be fairly easy to add. I'm not sure the dev_setup.sh should perform the upgrade since it'll affect other packages in the system than the ones required by mycroft.

**Comment by assasen11** [comment]
This is working now. as along as `sudo yum install epel-release` is done first everything will work.  I think epel-release just updates the repos for the newest possible common packages. I tested this on a fresh install of Centos 7 minimal multiple times. This should also work on Redhat and fedora but I have not tested there yet.
