### ISSUE TITLE
Wolfram Alpha Skill fails when results have 'did you mean?' queries

### ISSUE THREAD

**Issue by Wolfgange3311999** [MycroftAI/mycroft-core#192]
For instance, when asking for "What is a power supply?", Mycroft will respond 
"I don't understand your request". This is because Wolfram only provides optional similar alternatives such as "What is a power". I think that in this scenario Mycroft should automatically send another request to Wolfram with the top similar alternative query and notify the user of this. So for example, 
"Hey Mycroft, what's a power supply"
"I am searching for a power supply"
"Assuming you asked about a power, a power is the possession of controlling influence."

Even though this was wrong in this case, I can see it being better than a simple, "Sorry, I didn't understand your request."

**Comment by ethanaward** [comment]
@Wolfgange3311999 In order to properly implement this to give feedback to the user, I feel like we would need a dialogue feature, so that the user can select an option from possible `Did you mean...`s. I can make a basic version of this that works when there is only one `did you mean`, but that wouldn't cover all cases.

**Comment by Wolfgange3311999** [comment]
Even though it still (intentionally) fails on multilpe `didyoumean` responses, marking as closes since it has been dealt with for when there is only one.
