### ISSUE TITLE
dev_setup.sh not working

### ISSUE THREAD

**Issue by Aiki-bot51** [MycroftAI/mycroft-core#2072]
im trying to install Mycroft on windows 10.

I tried using git bash and ubuntu, but the same problem. after cd Mycroft-core/, I inputed dev_setup.sh, after that always goes the same error
![mycroft problem dev_setup](https://user-images.githubusercontent.com/48476126/55169815-03b41580-51a8-11e9-8471-d4cb766e9714.PNG)

and I don't know what to do....

**Comment by andlo** [comment]
I think you need to run WSL on your windows. Either Ubuntu or Debian in WSL. Tht gives you a full blown ubuntu or debian. I have installed mycroft in WLS on my windows 10 and dont have any issues about that - except that audio and mic isnt working on WSL on windows…..But for coding and testing with the CLI client it is OK.
Audio and mic could be made working by adding pulseaudio to the WSL and pulseaudio on windows. But I hassnt played with - only reading about it.

**Comment by Aiki-bot51** [comment]
What is a wsl ( sorry still new to python)

**Comment by Aiki-bot51** [comment]
Wait lemme try that

**Comment by Aiki-bot51** [comment]
Still not working

**Comment by penrods** [comment]
I do run Mycroft-core under WSL (Windows Subsystem for Linux).  I use Ubuntu.  However there are some big caveats.

The biggest thing -- WSL had NO audio support.  No input, no output.  So all you can hope for is a command line interaction.  If you want to talk to Mycroft, this is not the answer for you.

If you are OK with that, then you should be able to install.  It has been a few months since I installed it from scratch, so there might be a few hitches.  Hints include:  Don't build mimic -- that is a waste of time and will crash.

You also need to override the default mechanisms for playing audio files.  You can do that via this file:
`/etc/mycroft/mycroft.conf`
```json
{
   "play_wav_cmdline": "echo %1 >> /tmp/mycroft_play_wav.log",
   "play_mp3_cmdline": "echo %1 >> /tmp/mycroft_play_mp3.log"
}
```

There might be a few other things you have to tweak that I'm forgetting.  This is definitely in _experimental_ territory.

**Comment by Aiki-bot51** [comment]
so what can I do? to intergrate Mycroft into windows 10? with audio support?

**Comment by penrods** [comment]
Start programming.  Either for Microsoft (adding audio to WSL) or porting Mycroft to Windows.

If you are just looking for instructions, they don't exist yet.

**Comment by Aiki-bot51** [comment]
wow..... that is both funny and out of the box answer. thx for the help so far.....

**Comment by Aiki-bot51** [comment]
but @andlo up there he said something about pulseaudio any idea? and what should I change to make it work even without audio?

**Comment by andlo** [comment]
look at this https://community.mycroft.ai/t/experimental-mycroft-on-wsl-with-pulseaudio/5464

**Comment by Aiki-bot51** [comment]
@andlo what does this mean? what should I do?
![pulse audio](https://user-images.githubusercontent.com/48476126/55288455-406b5100-53e2-11e9-9f68-a7dd4c8b8424.PNG)

**Comment by Aiki-bot51** [comment]
what is this??? how can I fix it? @andlo @penrods 
![error checkout](https://user-images.githubusercontent.com/48476126/55288771-ba9dd480-53e6-11e9-8bcf-3a63dec038ac.PNG)

**Comment by forslund** [comment]
The last error message suggest it ran out of disk space. You can try without mimic for now by first deleting the mimic subfolder

`rm -rf mimic`

and then running dev_setup.sh with the `-sm` flag to skip mimic:

`./dev_setup.sh -sm`

**Comment by Aiki-bot51** [comment]
How do i set it so that ubuntu's main saving location is driver D instead of C

**Comment by Aiki-bot51** [comment]
the "rm -rf mimic" doesn't do anything

**Comment by Aiki-bot51** [comment]
so what can I do to make it listen to voice command using pulse audio @andlo I followed your instruction then it 
![pulse audio](https://user-images.githubusercontent.com/48476126/55290784-d1055980-5401-11e9-8bbe-2217b217e931.PNG)

**Comment by andlo** [comment]
@Aiki-bot51 I cant really help in this - I could only point you to a forum post that were about running mycroft on VSL and using puleaudio. 

You could ask in the forum post i referred to or write a new post. 

I would recoment installing on a raspberrpi instead of trying to install mycroft on windows.

**Comment by Aiki-bot51** [comment]
I see..., would it work with google aiy voice kit?

**Comment by andlo** [comment]
Yes it works with google Voice Kit V1 but not fully out of the box. Install Picroft Image and update then it will work.

**Comment by penrods** [comment]
I don't wish to dissuade you from trying Mycroft, by the way!  But unless you are the type of person who enjoys breaking new ground on their own, this isn't something that is supported.  Working on a known-good platform like Picroft sounds like it would be a better option for you.

(And, personally speaking, I don't want to leave my laptop on all the time to act as a voice agent.  Low-cost hardware such as Raspberry Pi is much better suited for this.)

**Comment by forslund** [comment]
Since there's been no more communication the last year I'll close this issue now.
