### ISSUE TITLE
env: IS_TRAVIS is not really needed

### ISSUE THREAD

**Issue by cclauss** [MycroftAI/mycroft-core#2243]
https://github.com/MycroftAI/mycroft-core/blob/d1915d3f95a5dc31413e7621798695b0aa719168/.travis.yml#L35

Travis CI already defines both __$CI__ and __$TRAVIS__ as __true__
https://docs.travis-ci.com/user/environment-variables/#default-environment-variables

**Comment by forslund** [comment]
Thanks for pointing this out. We should defenitely of the existing ones. we currently only use it in the [dev_setup.sh @ L131](https://github.com/MycroftAI/mycroft-core/blob/dev/dev_setup.sh#L131) and in [scripts/prepare-msm.sh @ L50](https://github.com/MycroftAI/mycroft-core/blob/dev/scripts/prepare-msm.sh#L50)

I think we should probably use the `$CI` one since we've got some automations that are not Travis that defines the IS_TRAVIS so CI would be more appropriate I think.

Feel free to submit a PR otherwise I'll mark it down for things to handle after my vacation.
