### ISSUE TITLE
Arbitrary Code Execution

### ISSUE THREAD

**Issue by larrycameron80** [MycroftAI/mycroft-core#2307]
Arbitrary Code Execution
Vulnerable module: pyyaml
Introduced through: pyyaml@3.13, msm@0.8.3 and others
Detailed paths
Introduced through: MycroftAI/mycroft-core@MycroftAI/mycroft-core#65bc1b9786461b2fafbb5d3dc49047f1d70f86f7 › pyyaml@3.13
Remediation: Upgrade to pyyaml@5.1.
Introduced through: MycroftAI/mycroft-core@MycroftAI/mycroft-core#65bc1b9786461b2fafbb5d3dc49047f1d70f86f7 › msm@0.8.3 › pyyaml@3.13
Remediation: Upgrade to msm@0.8.3.
Introduced through: MycroftAI/mycroft-core@MycroftAI/mycroft-core#65bc1b9786461b2fafbb5d3dc49047f1d70f86f7 › msk@0.3.13 › msm@0.8.3 › pyyaml@3.13
Remediation: Upgrade to msk@0.3.13.
Overview
PyYAML is a YAML parser and emitter for Python.

Affected versions of this package are vulnerable to Arbitrary Code Execution due to using the insecure yaml.load() function.

**Comment by krisgesling** [comment]
Hi Larry, 

Thanks for flagging this. Am I correct that the yaml.load() function needs to be actively used in order to exploit this?

I believe that we removed all instances of this function some time ago, but if we can bump the version of `pyyaml` without breaking anything that would likely be a good thing too.

**Comment by larrycameron80** [comment]
You're welcome. Yaml need to be loaded in order to exploit. Attempt an upgrade and let me know if any issues.

**Comment by forslund** [comment]
PyYAML has been updated to 5.1.2. Closing this issue.
