### ISSUE TITLE
Use of side libraries in mycroft-core

### ISSUE THREAD

**Issue by jumper047** [MycroftAI/mycroft-core#2387]
Hi!
I'm think about adding support of russian language to mycroft. One of the dificulties with russian - normalization. There is a library, https://github.com/kmike/pymorphy2, who can tremendously ease this task. So, the question is - is it acceptable to use side libraries inside mycroft core?

**Comment by forslund** [comment]
Hi, if there is a good reason like this and the requirements aren't too heavy it's ok to include.

We've split out most of the language tools into the repo [lingua-franca](https://github.com/MycroftAI/lingua-franca/) and will hopefully in the coming months start using that instead of the code inside mycroft.

You might want to ask the maintainers there as well for their policy. @JarbasAI I think is one of the maintainers and and probably the source of the idea to extract the code. He might have an opinion.

**Comment by forslund** [comment]
I'll close this issue now since there's been no follow up questions the last couple of days I'll close the issue. If you have more questions feel free to reopen the issue. You can also reach out on the [mycroft-chat](https://chat.mycroft.ai)
