### ISSUE TITLE
NPR skill issue

### ISSUE THREAD

**Issue by ChristopherRios7** [MycroftAI/mycroft-core#24]
There is an issue with the NPR news skill, there is no way to stop this skill when it is activated. You cannot stop the skill by clicking the button.

The only way to stop it, from my experience is to SSH the device and perform 'sudo reboot'.

**Comment by jdorleans** [comment]
NPR skill uses **mpg123** process to run the mp3 stream from NPR. To stop it we need to kill that process. Today, we do this by sending a command to the NPR Skill to stop once you press the button (make sure you have the latest core version). However, there is a knowing hardware bug that prevents the pressing action to work and you'd have to turn the encoder instead. Please, try that as well and let me know if it works.

Also, it is still on our roadmap to implement the **mycroft stop** voice command.

**Comment by aatchison** [comment]
Unless I'm mistaken, my rather hackish method to stop skills with the
encoder has been removed, to be replaced with StopSkill implementation

**Comment by jdorleans** [comment]
@aatchison you're right, the flow should be:
1. press button
2. enclosure receives and sends the stop cmd to all skills
3. all skills perform the stop operation (in the case above, NPR will stop by killing the process its using -  mpg123)

It's important to note though, the **enclosure** process **must** be running. So we'll be able to detect the button pressing action (remember the hardware issue, it might be a encoder turn instead of pressing).

**Comment by aatchison** [comment]
Let's integrate the stop event functionality into the "Mycroft Stop" skill, then it could come from where ever:)

**Comment by jdorleans** [comment]
Yes, the basic structure, and I believe most part of it, has been done awhile ago. Now, it's a matter of creating and prioritizing the general "Mycroft Stop" task.
