### ISSUE TITLE
Support snap packages without using a parallel branch or modifying mycroft-core,

### ISSUE THREAD

**Issue by aatchison** [MycroftAI/mycroft-core#246]

**Comment by rahmanshaber** [comment]
is there any work to build a snap package???

**Comment by rahmanshaber** [comment]
making snap will attract more user and reduce the difficulties of installing with git.
i am now installing and compiling it from aur and it is taking a hell of time(20 min past,still building) to compile in my old pc.
i really want use mycroft daily but every time it gets update i need to recompile .

**Comment by MatthewScholefield** [comment]
@rahmanshaber I 100% agree which is why I spent some time researching if it was possible. Right now, there's still a lot of hurdles left before it would become feasible.

As for you specifically, I'm assuming due to how AUR is written, it forces mimic to always rebuild. I recommend you try out using git install because using that you will never have to recompile for any updates.

**Comment by rahmanshaber** [comment]
ok .i am now trying it.

i would suggest you can contact with canonical to help you on that snap package(as mycroft is popular,and they will help i think).they helped skype,spotify etc.

or give a try with flatpack??

thanks for the support and instant reply.

**Comment by MatthewScholefield** [comment]
@rahmanshaber Trying flatpak is a good idea. If I remember correctly (which isn't all too common xD), I sent a message to the #snappy channel on freenode and didn't receive after a day or so. Regardless, I'm going to create a new issue for this so that anyone who wants to tackle this has a checklist.
