### ISSUE TITLE
recognizer_loop:audio_output_start (and end version) message wrong tense

### ISSUE THREAD

**Issue by FruityWelsh** [MycroftAI/mycroft-core#2494]
Shouldn't the message: '''recognizer_loop:audio_output_start''' and '''recognizer_loop:audio_output_end''' be ''''recognizer_loop:audio_output_started''' and '''recognizer_loop:audio_output_ended''' to keep in line with the [messagebus guidelines](https://mycroft-ai.gitbook.io/docs/mycroft-technologies/mycroft-core/message-bus) that all post-action notifications be in past tense?

**Comment by forslund** [comment]
Hi, you are technically correct. In addition they don't use the `mycroft.xxx` notation that we use nowadays.

These messages has always been around (since long before we made any specification of how messages should look) , they remain mainly to keep compatibility with those skills  and enclosures that are using them.

I do think we need to keep them for a while more but we should add a couple of new messages that are sent at the same time as those to modernize. Running the old messages in parallel with the new for a while, and then phase them out in a year or so.

Suggested replacements:
`recognizer_loop:audio_output_start` -> `mycroft.audio.speech.started`
`recognizer_loop:audio_output_end` -> `mycroft.audio.speech.ended`

`recognizer_loop:record_begin` -> `mycroft.voice.record.started`
`recognizer_loop:record_end` -> `mycroft.voice.record.ended`
`recognizer_loop:wakeword` -> `mycroft.voice.wakeword.detected`
`recognizer_loop:sleep` -> `mycroft.voice.sleep`
`recognizer_loop:wake_up` -> `mycroft.voice.awoken`
`recognizer_loop:utterance` -> `mycroft.voice.utterance`

Let me know what you think

**Comment by FruityWelsh** [comment]
Those look much better to me. The only one I would have contention with is '''mycroft.voice.awoken''' because '''awoken''' would imply a notification that mycroft has awoken. I think either keeping the pretense verb '''wake_up''' or some variant would make more sense.

**Comment by forslund** [comment]
Right, I miss-remember...I was sure that message was sent when the listener had been awoken by a "hey mycroft wake up" command. the one I think of is actually called `mycroft.awoken` I'll update my previous list.

**Comment by forslund** [comment]
Closing Issue since we're archiving the repo
