### ISSUE TITLE
Relax dependency version requirements

### ISSUE THREAD

**Issue by PureTryOut** [MycroftAI/mycroft-core#2517]
I'm packaging Mycroft for Alpine Linux, and am currently working my way through all the Python dependencies. I noticed that mycroft-core currently expects really specific versions of requirements (e.g. `padaos==0.1.9`), instead of just the minimal version it needs for it's functionality. This makes it hard to package, as rolling distributions tend to package the newest version of every library.

This means that even newer Mycroft libraries don't get used. For example [`precise-runner`](https://github.com/MycroftAI/mycroft-precise) 0.3.1 exists, but mycroft-core still expects 0.2.1, so no one actually gets to use the improvements made there.

Please start relaxing the version requirements, do something like `precise-runner>=0.2.1`. It'll make it a lot easier for rolling distributions to package mycroft and makes sure people get the benefits of all improvements made to all libraries.

**Comment by forslund** [comment]
Hi thanks for starting this discussion.

We've been sticking with fixed versions to make sure upstream bugs don't affect us and try to upgrade in a controlled fashion. We've been hit a couple of times where some users get problems due to a specific version of a package containing a new bug. it usually goes away after a while.

precise-runner hasn't been updated because of issues with the precise-engine 0.3.1 so we can't actually move to that version. (We upgraded and then reverted the upgrade due to issues with it)

One alternative is to use the ~= to make sure the api is the same but including bugfixes / non-breaking issues but again that's no guarantee and a person installing one day can have an environment that works flawlessly while an user installing the next day has terrible issues.

I would love to see your packaging and help in any way we can. The common issue is the install of dependencies by skills. On debian based systems we've used dh-virtualenv to package a sandboxed virtual environment that skills freely can install their dependencies into. I'd very much like to see your solution.

**Comment by PureTryOut** [comment]
> I would love to see your packaging and help in any way we can.

Awesome, thanks! That is a great response! Do note that it's very WIP, I literally just started this today. You can find the packaging here https://gitlab.alpinelinux.org/PureTryOut/aports/commits/testing_mycroft.

> We've been hit a couple of times where some users get problems due to a specific version of a package containing a new bug

Known problem for most applications out there. However, normally the distribution maintainers should make sure the package works on their distro, and work together with upstream to accomplish this. So they shouldn't push a package version without testing it and if something breaks with newer libraries, they should work to resolve that themselves _together_ with upstream. Then again, I can understand it being annoying if distro users go to upstream to report their distro bugs rather than to the distro issue trackers, not much to do about that besides informing the user they are reporting it in the wrong place.

**Comment by ChanceNCounter** [comment]
The trouble (imo) is that when such a thing happens to a Linux user, it's annoying, but when it happens to a general user *on a Linux device*, it's their worst nightmare. They have to call somebody else to deal with it, it's stressful, it feels to the layperson like the machine is taunting them.

Better when deps Just Work.

**Comment by PureTryOut** [comment]
> but when it happens to a general user on a Linux device

You mean for example the official MyCroft devices? I mean sure, but I would hope those are extensively tested before shipping any updates to them. In case of such devices, you can just ship the minimum supported deps. They are a lot more static anyway.

My case is more for running Mycroft on your desktop for example in combination with the Plasma widget. In this case updates should of course still be tested by the distribution maintainers, but it's less of a problem when it breaks.

**Comment by forslund** [comment]
Sorry for the real long delay. Totally slipped my mind.

There are a couple of things that makes the strict version dependencies make sense in my mind

1. Currently most of usage is installed direct from the git repository and not from a package so to be able to support and make sure that each install an end user makes is 

2. The requirements listed here is what the packaging for the mark-1 devices use and to make sure it builds what is tested we need to keep the requirements strict.

Are you building the package from the setup.py script?

I wonder if we can add a "loose requirements" flag (or environment variable) converting all the == to >= signs when read? or a flag to allow a separate requirements.txt file.

**Comment by PureTryOut** [comment]
> Are you building the package from the setup.py script?

Yes I am. I'm fine with a  loose requirements flag or a separate requirements.txt file, just any way that allows me to package it for <insert some distro here> without having to package separate versions _specifically_ for MyCroft.

**Comment by ChanceNCounter** [comment]
> You mean for example the official MyCroft devices? 

I didn't (and I am also sorry for the long delay, I missed this in subscription spam)

There have been a few times, over the years, where an enterprising community member packages Mycroft and (understandably, it's FOSS) winds up abandoning their package.

This gets annoying, because end users mistake those for official packages, which they aren't, and the users come to the forum or Mattermost expecting support. Mycroft staff can't help because it's not their package, and the rest of us can't help because we don't know what That Fool was doing 18 months ago when they packaged Mycroft for Android =P

That's the only reason I brought it up. When it's labeled, "...for Android," or etc, people will try it who are decidedly *not* Linux users.

Whether that's a Thing for you will, I suppose, depend on the audience. Certainly there aren't as many people out there throwing Alpine in a box as there are with rooted phones.

**Comment by PureTryOut** [comment]
In case of Android, it'll never be "official for Android" as long as it's not MyCroft itself doing it. However in the case of Linux distributions, Mycroft doesn't _have_ to do it themselves. I'm doing it purely for Alpine, but you got to think of the other distributions too. Distributions like Debian with well set guidelines for adding packages to their repos, maintaining them and abandoning. A package there won't just "be abandoned" with users then being stuck with non-working packages, that's just not how the Linux distribution model works, there are safeguards in place per distro to prevent that from happening ;)

I do get your point, getting bug reports from users not using your packages is annoying, but it means a lot more people will be able to enjoy what MyCroft can do right on their desktop, from sources they already trust (the distribution repositories). And besides, when problems appear in packages in distributions, the maintainers tend to do their best to resolve them, besides just reporting it upstream.

Like I said, I'm fine with a special flag which loosens the restrictions or a separate requirements.txt file, so you can keep your strict requirements in place for the devices and such.

**Comment by PureTryOut** [comment]
Good to note, by replacing the `==` for `>=` in `requirements.txt` myself, I got MyCroft to work with purely packaged packages, including some newer versions than the requirements file specifies. There is an issue with getting `mycroft-audio` working, but I successfully registered the device and see results of queries I ask it via my mic in mycroft-cli-client.

**Comment by forslund** [comment]
This is now allowed using the MYCROFT_LOOSE_REQUIREMENTS environment variable (see #2562). Closing this issue.
