### ISSUE TITLE
Generic house automation skill

### ISSUE THREAD

**Issue by grahamreeds** [MycroftAI/mycroft-core#253]
While the Philips light bulb is a good start, a more generic approach is needed.
For instance: "Mycroft - turn the lights on".  

Firstly mycroft needs to know which room you are in - if there is one mycroft with it's single speaker then logically it can only automate that room.  If you have multiple units and you address the one in the room you occupy then how to prevent another unit from overhearing you and turning the lights on in another room.

Another is context: "Mycroft - turn the patio lights on" .  Need to differentiate between different lights.

Beyond lights, there is others;
- Heating: "Mycroft - turn the heating on", "Mycroft - is the heating on?", 
- Home comforts: "Mycroft - draw the curtains"
- Security: "Mycroft - Lock down"

A general search quickly turned up https://home-assistant.io/ which may help.

**Comment by marksev1** [comment]
You know what would be nice, if this skill would have an "option" inside of it to either tie in completely with home-assistant, or output the configuration via mqtt. Like dunno turn on-off kitchen light

mqtt topic

home/kitchen/light/on
home/kitchen/light/off

So even if it would auto-generate the rooms from home-assistant. That it would make the control outputs via mqtt (btw home-assistant supports mqtt too). But using mqtt instead of some protocol that  home-assistant uses would make it more generic for other home automation software..Well it would at least be nice to have it optionable.

What about the protocol with which Mycroft would communicate with homa-assistant, is it via home-assistants api? Where can I read about it?

**Comment by marksev1** [comment]
I think this should be closed since there is now a MQTT Skill available which could be used as a generic home automation skill.

**Comment by forslund** [comment]
As @marksev1 pointed out (ages ago, sorry about that), there are a couple of home automation skills around now: MQTT, Wink, home-assistant.

Closing
