### ISSUE TITLE
messagebus_test.py hangs forever

### ISSUE THREAD

**Issue by PureTryOut** [MycroftAI/mycroft-core#2570]
I'm trying to run the tests on an Alpine Linux system with system packages, using version 20.2.2.

After applying https://github.com/MycroftAI/mycroft-core/pull/2569, the tests in `test/integrationtests/messagebus/messagebus_test.py` starts but hangs forever and never finishes.

**Comment by forslund** [comment]
Thanks for flagging. this is a test that hasn't actually been in use while I've been involved with Mycroft so I'm not sure of the state of it at all. It's sort of replaced by voight kampff in one way since VK won't work with a failing messagebus...

**Comment by PureTryOut** [comment]
That is interesting, as running `pytest` definitely still runs that test.

What would the recommend way of running all the tests be then nowadays? Can Voight Kampff even be ran locally?

**Comment by forslund** [comment]
pytest without specifying the unittest directory will likely catch it yeah. The big issue seems to be that the service start command isn't up to date. The message method tests are also outdated and shouldn't be in the file since those are more along the lines of unittests.

got the inital test passing using
```
self.pid = Popen(["python3", "-m" "mycroft.messagebus.service"]).pid
```

and then I just removed the second test case.

Could you test that and see if it solves it for your setup as well (and maybe update your PR if it works)?

VK can be run locally, either using the Docker file or against a live Mycroft instance.

**Comment by PureTryOut** [comment]
Yup that did the trick, I've updated my PR to fix this.

I'll look into running VK locally, but using Docker definitely isn't an option for this. A live Mycroft instance is also a problem...

**Comment by forslund** [comment]
Thanks, will merge as soon as the Autobots are done testing :)
