### ISSUE TITLE
incorporate audio-accuracy-test into existing test suite

### ISSUE THREAD

**Issue by clusterfudge** [MycroftAI/mycroft-core#258]
should be implemented as a unit test with assertions.
should run with existing unit tests
should not be in it's own top level directory.
likely involves some static data set (to which we can append over time).
data should not be checked into git, should be fetched from source and cached locally in a directory that is .gitignored

**Comment by Wolfgange3311999** [comment]
I'm a bit concerned to do the top two. For the top one since the result gives a % rather than a binary answer should we just choose a percentage a bit lower than what it is now? And for the second one, my only concern is that others won't want it to spend 2 minutes or however long it takes for that test. Then again, if that's the case they could just remove the cached audio directory.

**Comment by clusterfudge** [comment]
for 1, is there a realistic scenario where we can drive for 100% and then turn that into a strict assertion? If not, we could say that we require > C, but that leaves wiggle room for breaking things while fixing others, and I'm not a huge fan of that non-deterministic behavior.

for 2, that's fair. Maybe we want to introduce a concept of slow tests that only run as part of pr/release builds? that way devs can still run the usual unit test suite locally. My main goal is to get this automated to prevent regressions.

**Comment by Wolfgange3311999** [comment]
For 1 I can try recording a set of loud and close samples with no background noise to shoot for 100%. Relating to that, I can record a few samples of things that are clearly not the wake word (ie. "micro", "hey michael", and "hey mike") so that the false positive test with those samples should always return 0.

And yes, for 2 I think that would be good. Perhaps `./start.sh unittest --thorough` or another parameter that makes more sense.

**Comment by Wolfgange3311999** [comment]
@clusterfudge Any thoughts on the directory and filename? `test/client/speech/mic.py`?

**Comment by krisgesling** [comment]
Hey all, this seems to be focused on Precise and we're doing a bunch of work on that currently but over in that repo. So going to close this but if there's elements that you think we might be missing then let us know.
