### ISSUE TITLE
Moved: New Skill: CatchAll Fallback asks to repeat phrase when no intent determined

### ISSUE THREAD

**Issue by auwsom** [MycroftAI/mycroft-core#2612]
Following the docs on Fallbacks here: https://mycroft-ai.gitbook.io/docs/skill-development/skill-types/fallback-skill, and the example here: https://github.com/forslund/fallback-meaning, and figuring out the correct syntax by trial and error here:  https://github.com/MycroftAI/mycroft-core/issues/2611, and adding the following lines of code (the second part replacing the Arthur Dent intent finding), the fallback now asks a follow up question 'What was that?' whenever an intent cannot be determined. (several variation on that vocab could be added to the `self.speak_dialog('CatchAllFallback')`

```
from mycroft.messagebus.message import Message
.....
    def handle_fallback(self, message):
        self.speak('what was that?')
        self.bus.emit(Message('recognizer_loop:wakeword', {"utterance": "homie"}))
        return True
```

**Comment by auwsom** [comment]
I recommend this be a skill in the marketplace or possible a default skill in the 'cannon'.

**Comment by forslund** [comment]
Might be something that could be added to the [fallback-unknown skill](https://github.com/mycroftai/fallback-unknown) Maybe move the issue there or to the [mycroft-skills](https://github.com/mycroftai/mycroft-skills) repo (since this is more skill related than core related).

Glad that my old example skill came in handy :)

**Comment by auwsom** [comment]
Ah right, the skills repo, yes.. will move.

Hey, I'm actually debugging it right now.. I didnt realize the it is overriding other skills until I started working on another one. Any suggestion on how to catch just everything that isnt a skill intent? I thought that was what the fallbacks did, but your example uses several word verification steps.

**Comment by auwsom** [comment]
moving this to https://github.com/MycroftAI/mycroft-skills/issues/1340
and closing

**Comment by forslund** [comment]
To answer your question, the fallbacks have priority (1-100) so a fallback with the prio 1 will be checked before a fallback with prio 2.

The example has the prio 1.

```python
        self.register_fallback(self.handle_fallback, 1)
```

 which is good to show it's executing BUT is bad since 1 is before a lot of important things:

before the Padatious intent parser which is prio 10 I think. The fallback-unknown is set to prio 100

```python
        self.register_fallback(self.handle_fallback, 100)
```

So you might want to set your skill to 99 to be just before the fallback-unknown but let all other skills try to match the sentence.

See the api documentation for some guide to the ranges: https://mycroft-core.readthedocs.io/en/latest/source/mycroft.html#fallbackskill-class
