### ISSUE TITLE
Add VK Step: Given <some> setting is <value>

### ISSUE THREAD

**Issue by krisgesling** [MycroftAI/mycroft-core#2633]
Would be great to have the ability to set a Skill setting value as a Given step for a Voight Kampff test.

Eg: 
```
Given the custom news feed setting is https://example.com/
When when the user says "what's the news"
Then the News Skill will play that feed
```

Would it be sufficient to overwrite the `settings.json` file or is there a chance it will update from remote settings during the test?
Do we need to mock the settings object instead?

**Comment by forslund** [comment]
settings.json can be overwritten but the skill need to be informed that it should reload settings from disk. Perhaps backend settings updates should be turned off in the skill tester to make sure no overwrites occurs?

Back in April or so I wrote a demo for launching the skills process through a wrapper (the test mocked the datetime utils). I wonder if such a wrapper could be an alternative to allow injecting things more reliably.

**Comment by JarbasAl** [comment]
how about a global flag to disable settings sync? some users just dont want/like it, and it would help in tests (avoiding the overwrite issue)

why do i dislike skill settings?
- the websettings overwrite my local changes (breaks a few of my most important skills) related https://github.com/MycroftAI/mycroft-core/pull/2707 and https://github.com/MycroftAI/mycroft-core/pull/2698
- sync to all devices, messes up stuff like my Voip skill since i cant set up different accounts per device
- privacy reasons, once the 2way sync is reimplemented stuff like creds (changed on device) might get uploaded to you, in this case creds shouldnt even be in settingsmeta, but we dont control what others dev do and forking should not be a requirement for privacy


while this stuff isnt fixed/implemented i essentially stopped using websettings at all. not an issue for me, but i would like other people to be able to use my skills.....
   
dont mean to hijack this issue, but this simple flag would solve other issues and part of this one

**Comment by forslund** [comment]
I assumed some such config existed. If it doesn't it should definitely be added.

**Comment by forslund** [comment]
Closing Issue since we're archiving the repo
