### ISSUE TITLE
Add festival TTS engine

### ISSUE THREAD

**Issue by jmontane** [MycroftAI/mycroft-core#2640]
Hi,

I'm working adding Catalan language support to Mycroft.

Google and espeak voices for Catalan are horrible, really bad. 

There are good Catalan voice for festival TTS, but they are not converted to flite. So I request to add festival TTS engine to mycroft-core.

**Comment by JarbasAl** [comment]
see https://github.com/HelloChatterbox/text2speech

if the mycroft team wants to make this a requirement it is pretty much compatible with mycroft, otherwise you can almost copy paste the code, some minor changes will allow you to submit a PR integrating that in core

https://github.com/MycroftAI/mycroft-core/pull/2594 is probably the best approach, you can either copy code from repo above or use it as a dependency

**Comment by jmontane** [comment]
I'm not a programmer, but I tried my best with [this PR](https://github.com/MycroftAI/mycroft-core/pull/2641)

**Comment by krisgesling** [comment]
Festival TTS support now added thanks to @jmontane :tada:
