### ISSUE TITLE
sensible-editor required for mycroft-config

### ISSUE THREAD

**Issue by FruityWelsh** [MycroftAI/mycroft-core#2664]
mycroft-config's ```set``` option fails if sensible-utils is not installed.
after install there was error stopped

```
Operating System: Manjaro Linux
Kernel Version: 5.7.15-1-MANJARO
OS Type: 64-bit
```

**Comment by krisgesling** [comment]
Thanks for reporting FruityWelsh, we'll need to make sure we have the right package name for each of the distributions supported by the install script. If  no one gets to it beforehand I'll take a look after we release mycroft-core v20.08

**Comment by FruityWelsh** [comment]
no problem, for arch based systems it is available in the aur as ```sensible-utils```, I didn't find it in the man manjaro repo unfortunately.

**Comment by forslund** [comment]
I think it's intended to work without sensible-editor, the `set` action should just require `jq`.

Do you have the exact error message?

It does a lookup for editor the idea is that it should use
1. Command line stored in $EDITOR
2. If sensible-editor exists, use that
3. Use nano

Without sensible-editor and without nano `set` works for me (but `edit` doesn't)

possibly we should add a step 4 using `vi` since it's basically everywhere... but that may generate a lot of new issues...

**Comment by FruityWelsh** [comment]
```which: no sensible-editor in (/home/andruid/.pyenv/plugins/pyenv-virtualenv/shims:/home/andruid/.pyenv/shims:/home/andruid/.pyenv/bin:/home/andruid/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/var/lib/flatpak/exports/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl)```

is what it gives me when ```sensible-utils``` is not installed, with no error when it is

my EDITOR value was also not set, after setting it it does work without ```sensible-utils```

**Comment by chanjuping** [comment]
Hi. Adding that in openSUSE Tumbleweed, I have to install sensible-editor from dpkg. Option works after that.

`sudo zypper in dpkg`

**Comment by forslund** [comment]
Closing Issue since we're archiving the repo
