### ISSUE TITLE
Install to /opt from setup.py

### ISSUE THREAD

**Issue by devinhedge** [MycroftAI/mycroft-core#2747]
**User Story**
As a Mycroft administrator/installer,
I would like Mycroft to be installed into the standard directory for non-system daemons
So that I can run with daemon level permissions and use systemd

**Acceptance Criteria**
I know this will be done when:

1. Mycroft-core is installed in /opt/mycroft
2. A user is created as a service account
3. Mycroft can be started, topped, etc. from anywhere

**Related Feature Request**
This is the first part of building [systemd support](https://github.com/MycroftAI/mycroft-core/issues/346)

**Comment by devinhedge** [comment]
I'm not sure how to assign this to myself.

**Comment by el-tocino** [comment]
You can't assign to yourself since you're not attached to the repo.  Fork to your own, and then you can later submit PR's from there.

**Comment by forslund** [comment]
Wouldn't this just be to create a venv in /opt and then run the setup.py from that venv? Not sure it's setup.py's job to decide where it's installed since it requires an existing python env.

As a sidenote. We've had quite a bit of discussions around the systemd part and it was decided (but could of course be changed) that mycroft-core should not include the systemd files and scripts, instead we've added hooks for systemd or other managing systems (be it a desktop launcher or another startup manager) to use.

**Comment by PureTryOut** [comment]
Note that you can already tell `setup.py` where to install things. As an example, see [how I install MyCroft in Alpine Linux packaging](https://git.alpinelinux.org/aports/tree/community/mycroft-core/APKBUILD#n43).

Basically it's just doing `python3 setup.py install --root="<wherever you want to install it too>"`.

**Comment by krisgesling** [comment]
Hey Devin, thanks for getting involved with Mycroft. It's good to hear a clear outline of your needs.

I'm closing this as it seems like this is not needed for `setup.py`. In terms of systemd we want to keep mycroft-core agnostic to how it is being packaged. Currently a lot of that is mixed into core, but we are actively working to extract it out. These will in future live in a repo specific to that type of packaging eg a device like the Mark II or a packaging format like .deb or .snap.

If you haven't seen it already, definitely checkout [j1nx's systemd work](https://github.com/j1nx/mycroft-systemd) too.
