### ISSUE TITLE
Ability to play a sound instead of an utterance

### ISSUE THREAD

**Issue by dalgwen** [MycroftAI/mycroft-core#2755]
**Is your feature request related to a problem? Please describe.**
Despite all my efforts, the wakeword system generates too many false positive.
(As I'm french, I'm using custom wakeword with snowboy because precise "hey mycroft" is too english sounded for my family. But it's far from good).
Thus, I get many mycroft errors or "I don't understand something something" and it's... How can I say it ? getting on my nerves ;-)
Afeter discussion with other Mycroft's user on the related PR page, this feature could be extended to allow Mycroft skills to play sound.

**Describe the solution you'd like**
Ability to play a brief little sound instead of a complete utterance.
- Skills would have to add an optional meta information to theirs error utterrances (a new parameter to the speak method)
- A per skill, user configuration parameter could be used in order to not suppress every "final" messages if wanted, and focus on fallback skills for example.
- a global configuration parameter  could also be used to express all "final" utterance as sound

**Additional context**
I am ready to propose a merge request for this functionnality.

**Comment by dalgwen** [comment]
[Link to pull request](https://github.com/MycroftAI/mycroft-core/pull/2756)

**Comment by forslund** [comment]
I first through this should behandled in [fallback-unknown](https://github.com/mycroftai/fallback-unknown), which is triggered when no skill can handle an utterance. This would be a simple skill setting to just play an error sound instead of speaking "sorry I don't understand".

But your PR looks like it's more for error reporting and that might be a good idea.
