### ISSUE TITLE
Mycroft-Core 20.8.1 breaks Pandora skill

### ISSUE THREAD

**Issue by thejacer** [MycroftAI/mycroft-core#2842]
**Describe the bug**
Upon updating to Mycroft-Core 20.8.1 the Pandora skill stops working and continually asserts the skill isn't set up at mycroft.ai. My Pandora skill had been set up for weeks but this update broke it.

**To Reproduce**
Install 20.8.1
Try Pandora skill
Roll back to 20.8.0
Try Pandora skill

**Expected behavior**
Pandora skill will fail as if your login credentials aren't in the settings while using 20.8.1 but will succeed without error on 20.8.0

**Log files**

You may also include screenshots, however screenshots of log files are often difficult to read and parse. 

If you are running Mycroft, the [Support Skill](https://github.com/MycroftAI/skill-support) helps to automate gathering this information. Simply say "Create a support ticket" and the Skill will put together a support package and email it to you.

**Environment (please complete the following information):**
 - Device type: Raspberry Pi 4 B
 - OS: Raspberry Pi OS
 - Mycroft-core version: 20.8.1
 - Other versions: 20.8.0

**Comment by krisgesling** [comment]
Hey thanks for reporting this!

I just took a look at that Skills code and it's storing a whole bunch of local values in the Skill settings. 

mycroft-core 20.8.1 has a feature that prevents remote Skill settings overwrite local ones. 

So imagine you want to add your password to a Skills settings but don't want that synced to the cloud. Previously the remote setting would have overwritten your local changes, now it detects that the file has changed and leaves it alone. Unfortunately in this case, it means that the remote settings will never be pulled down locally.

So as an interim measure if you wanted to update to 20.8.1 you could add your username and password  to `~/.config/mycroft/skills/mycroft-pandora.mycroftai/settings.json`

But the real fix is that the Skill needs to be updated to store these values in the Skills namespaced filesystem instead.

**Comment by forslund** [comment]
@krisgesling are you sure this is an intended change? The two changes I've seen is the one that only update settings if there are changes in the remote and the option to disable skill settings download at all.

AFAIK local changes should not block downloading settings from home.mycroft.ai. (At least not intentionally)

**Comment by krisgesling** [comment]
You are correct - I misrepresented it.

The real issue is that the Skill was assigning empty strings to each value in the settings object, then expecting it to be overwritten:
https://github.com/MycroftAI/skill-pandora/pull/42/commits/9c369c8ecce6b8a1710de4003682000136a9aa0b#diff-8e2c1f727276d30ced72fa67cb848772a9802162bec39b42a8df5359fd063a4cL74-L84

So the remote settings were probably getting pulled down fine, but the local Skill was "initializing" the values on Skill load thereby reassigning them to nothing.

**Comment by forslund** [comment]
Aha, it looks like it expected the old (pre 19.08) Settings Object, which has a guard allowing settings parameters to be added  but not overwritten when called from the skill `__init__()`.

Can this be closed then or should we keep it open since it's a slight change in behavior, (even if the affected use case is from a couple of years back)

**Comment by krisgesling** [comment]
I was trying to fix the VK failures, but they're not going to block anything else since it's not a default Skill in the VK test suite. So I might just merge the update to mycroft-skills and call it a day...

**Comment by krisgesling** [comment]
Updated Pandora Skill is now in the Marketplace. Please reopen if you still see the issue.
