### ISSUE TITLE
Package as Flatpak

### ISSUE THREAD

**Issue by 12people** [MycroftAI/mycroft-core#2850]
In issue #1723, MyCroft was packaged as a Snap.

Unfortunately, Snap has a proprietary back-end, which is why no other distribution except Ubuntu (and its official flavors) bundles it by default. For free software enthusiasts, it's a no-go.

It'd be great if MyCroft could be packaged as a Flatpak too.

**Comment by ChanceNCounter** [comment]
I would be even happier if there were no such package, period, at all. Whatsoever.

**Comment by JarbasAl** [comment]
there are enough broken and unmaintained packages already, please dont subject us to the unavoidable storm of support requests when whoever makes it stops maintaining it, this keeps happening over and over again ....

**Comment by krisgesling** [comment]
Hey there, @12people - we are very open to distributing via Flatpak also.

The Snap started as a community effort and when it worked very quickly got outdated. We get the same thing from distro's  packaging Mycroft and not maintaining them. Then users come to our community for support and as you can see from the comments above, people get quite frustrated, and understandably so. The argument is made that Mycroft the company should handle this packaging, however you can't start something then expect someone else to maintain it.

We've since adopted the Snap package and it's now building off our CI so gets continually updated and pushed, but we haven't had time to fix the significant usability bugs. We try to label it as an Alpha release and warn people but even if you have to use dev flags to install it, it's hard to get people to read the docs.

I say all this ^^ to provide an explanation of the comments above, and hopefully avoid similar issues with Flatpak or any other packaging format that comes along. Mycroft is not opposed to any packaging format, so if you have experience packaging for Flatpak then we'd love to see what you or others can come up with. The key being not to publish or publicize it until it's really usable, we can set it up with CI/CD, and ideally that this has automated testing to check each build.

Thanks

**Comment by ChanceNCounter** [comment]
Possibly related discussion in #2851

**Comment by 12people** [comment]
I understand.

I guess I'll keep this feature request open, in case there's a willing maintainer in the future.

**Comment by Techcrafter** [comment]
Mycroft as a Flatpak would be awesome! I like Mycroft a lot, but I'm currently unable to use it cause I don't want to loose my wine installation (again). Providing Mycroft as a Flatpak would resolve this issue I think.
Snap would too, but I hate Snap because of it's "background", so Mycroft as a Flatpak would be awesome!

**Comment by ChanceNCounter** [comment]
A number of us are running both Mycroft and Wine just fine. The libjack problem is not clear-cut.

**Comment by Techcrafter** [comment]
How can you install Mycroft and Wine together? I tried it once and everything was just gone. But another point for Mycroft as a Flatpak is, that Mycroft would probably become a bit more "noticed" than before. A lot of users probably won't do this cli based stuff to get mycroft running. Installing a Flatpak is a lot easier (at least on the user side)!

**Comment by ChanceNCounter** [comment]
I'm sorry to report that the answer is, "Yep." I don't know if anybody has actually investigated the difference between systems where it works and systems where it doesn't. Wine might somehow depend on a different libjack on some distros, or else it might have to do with the order in which you install them permitting one or the other program to utilize the other.

I'm not qualified to diagnose, I'm just saying, the Wine thing isn't an across-the-ecosystem thing, which makes me think there must be *a* way to address without sandboxing Mycroft, which has pros and cons, or creating another third-party package, which (as noted above) has not been a positive experience for the community (certain very, very dedicated contributors excepted, like @PureTryOut's Alpine stuff, which is as necessary to running Mycroft on Alpine as it is well-attended by its creator-maintainer, and which avoids sandboxing Mycroft.)

**Comment by krisgesling** [comment]
Yeah I assume it only affects certain versions of wine and perhaps they've now moved away from the offending dependency. We added the big warning in the `dev_setup.sh` script because it's intended as a development setup script rather than end-user script anyway. Hopefully it encourages people to check the packages that will be removed and not just click yes. If it only lists the one package to be removed and not wine etc then you should be fine.

**Comment by forslund** [comment]
Closing Issue since we're archiving the repo
