### ISSUE TITLE
Status page for Mycroft packages / distributions

### ISSUE THREAD

**Issue by krisgesling** [MycroftAI/mycroft-core#2851]
**Is your feature request related to a problem? Please describe.**
Mycroft should be packaged by other projects into their systems and distributions however it's not clear to end users when things are still in development, or are no longer maintained.

**Describe the solution you'd like**
A "Service Status" style page that lists all known Mycroft packages / distributions, and their current (or latest known) state.
eg
Status | Package | Last Checked | Notes | Report a bug |
--- | --- | --- | --- | --- |
:green_circle:  | [Docker](#) | 2020-03-08 | | [Report a bug](#)
:warning: | [AUR](#) | 2020-03-01 | Warning this has been reported broken | [Report a bug](#)

**Comment by ChanceNCounter** [comment]
I love it! Perhaps an additional bug indicating whether a package is officially supported could be helpful (or just a disclaimer indicating that none of them are.)

**Comment by ChanceNCounter** [comment]
On the other hand, I'm not sure I agree that Mycroft "should" be packaged, as this almost always puts the user at the packaging party's mercy for updates. Mycroft is self-updating. It also might not be clear to end users whether a given package will sandbox Mycroft, and therefore whether a given package will support things like desktop control skills (or anything that tries to mess with the system or call out to dbus or otherwise act in privileged ways.)

**Comment by PureTryOut** [comment]
Note that there is [Repology](https://repology.org/project/mycroft-core/versions) which you can use to check package versions in the various distributions. I'm happy to say at least the Alpine Linux package is up-to-date :hugs:

**Comment by PureTryOut** [comment]
When we go by the Repology list, Alpine Linux is updated and I can personally confirm it works as expected :stuck_out_tongue_winking_eye: 

Manjaro package seems relatively updated (missing the last point release), but with no link to their packaging it's hard to determine what quality their packaging is. I can't find it on their Gitlab instance either, but then again I can never find anything on there.

openSUSE Leap and Tumbleweed are both outdated, I wouldn't recommend using it currently.

RebornOS seems updated. I have never heard of that distribution, and there is no link to their packaging so it's hard to determine their quality. I wouldn't recommend using it currently.

Solus is outdated, but less so than openSUSE. I still wouldn't recommend using it because of being so outdated.

**Comment by ChanceNCounter** [comment]
The Manjaro package was hand-added by a distro maintainer, and I've never been able to find it, either. I didn't know it had been updated.

**Comment by PureTryOut** [comment]
I found the [packaging for RebornOS](https://gitlab.com/rebornos-team/rebornos-packages/mycroft-core/-/blob/main/PKGBUILD) and it's... interesting... For some reason even though it's a distribution package, they still install it to a virtual environment and some weird location. I'd personally not use it, but YMMV.

Solus and openSUSE (even Tumbleweed!) are still outdated, their maintainers should probably be contacted and see if they can finally start maintaining their package...

Manjaro has not updated to 21.2.0 yet, not sure if they're planning to do that at all. I'm personally not a fan of Manjaro packaging at all so I personally don't have much faith in it :sweat_smile:

**Comment by forslund** [comment]
Closing Issue since we're archiving the repo
