### ISSUE TITLE
Mycroft screens not visible.

### ISSUE THREAD

**Issue by stmaus** [MycroftAI/mycroft-core#295]
I have mycroft running on Ubuntu 14.04LTS and it gives voice response but I don't have any interface screens when I run mycroft.sh start.

**Comment by Wolfgange3311999** [comment]
Currently Mycroft Core itself doesn't have a desktop interface. Running `./mycroft.sh start` begins several processes silently in these hidden terminal windows referred to as screens. To view one of these you can execute the following: `screen -r mycroft-skills` or one of the other two `mycroft-` screens.

Perhaps this should be made more clear on the readme since the term `screen` is a bit vague. By the way, if you would like a GUI in Ubuntu you can try installing @joshymcd's [fancy desktop UI here][1].

[1]:https://github.com/joshymcd/mycroft-electro

**Comment by joshymcd** [comment]
Disclaimer - fancy and in progress :)

**Comment by stmaus** [comment]
Thanks for the quick response. The main Mycroft page shows several devices including and Ubuntu desktop with what appeared to be a desktop interface. I have a hard time understanding the voice and was hoping to find a text response somehow.

**Comment by Wolfgange3311999** [comment]
@stmaus If you just would like to see what Mycroft responds, although not the prettiest, you can run the following in a terminal after starting mycroft: `screen -r mycroft-voice`.

**Comment by stmaus** [comment]
Thanks, I have it registered with Cerberus and I've just begun to play with it.

**Comment by aatchison** [comment]
Glad you figured it out! Closing issue.
