### ISSUE TITLE
Continuous Listening feature Like assistant

### ISSUE THREAD

**Issue by hanzala123** [MycroftAI/mycroft-core#2959]
A Very nice feature of assistant is the continuous listening feature. Which is basically after processing what was spoken, It turns on recording for speech to text. If it detect nothing it will go back to listening for wakeword. I also made an assistant Which had this feature before switching to mycroft. It is also quite natural. If you want to command some one something or ask them you don't call their name after every sentence.

So what i am proposing for is a feature which can be turned on or off. where mycroft listens for something after what was said by the user was answered. If something is detected then mycroft processes it other wise mycroft goes back to listening for wake word.

**Comment by krisgesling** [comment]
Hi there,

If you're writing a Skill, the `speak_dialog()` method has an optional argument `expect_response`. Setting this to `True` will activate the listener after the dialog has been spoken.

For more info see:
https://mycroft-ai.gitbook.io/docs/skill-development/user-interaction/prompts#returning-responses-to-the-intent-parser

However there is nothing that does this by default for any dialog that's spoken. One of the challenges to doing this is knowing whether a Skill has completed what it intends to do. For example a Skills intent handler might speak some dialog, go and process the request further, then report back some final information. In this case presumably you would only want the listener to trigger after the final information.

Does the speak_dialog argument meet your needs or were you looking for something universal?

**Comment by hanzala123** [comment]
Hi,
Thanks for the reply
I am looking for something universal, like if mycroft says "reminder for x to cancel say cancel the reminder." then it starts listening i don't have to call mycroft again to say cancel the reminder.
or if i said something and mycroft processed it then listen for a bit for a follow up request. This seems more natural as i said before because we don't call people by their name everytime we tell them something. I am looking for something like this [https://www.youtube.com/watch?v=OCxL-V2Zt8A](url)
What you said is indeed true. It a challenge to find out when a skill has finished and that's the reason i could not do it on my own. I though maybe the developer could give me some insight on this.

**Comment by krisgesling** [comment]
I can certainly understand the appeal however it's not something that the internal team will be working on in the near term. 

My thinking is that we'll need a model to categorize speech vs non-speech rather than wake-word vs non-wake-word. Then enter some special active mode that is very clear to anyone in the vicinity of the device that it is listening to everything being said. Keep x seconds buffer of recorded audio, and on speech detection grab the audio stream and send it to off to be transcribed.

I'll leave this issue open as a thread for others to join and discuss how this might happen or to give it a try if they are keen.

**Comment by hanzala123** [comment]
@krisgesling I don't really care about the speech or non-speech detection as I do not speak English in my home and google speech recognition deems my normal speech as non-speech. All I want is to find some way to know that a skill has finished processing and trigger recognizer_loop:record_begin after that. Any help would be very much appreciated.

**Comment by hanzala123** [comment]
Update: I was able to achieve what I wanted by making a skill and adding this
`  def initialize(self): 
       self.add_event('recognizer_loop:audio_output_end',
                   self.handler_mycroft_skill_handler_complete)
    def handler_mycroft_skill_handler_complete(self, message):
        self.bus.emit(Message('mycroft.mic.listen'))`

I know what you are thinking? I thought of the same thing. But for some reason this works and doesn't interfere with the skills I have tested it with.

**Comment by ChanceNCounter** [comment]
"speech vs non-speech" will remain a problem for those users who have Mycroft set to the language they speak at home, as well as for future multilingual functionality, so I don't think it's a long-term solution. Possibly better to classify it as "utterances vs non-utterances," where an utterance is speech *intended for Mycroft to process*, as opposed to everything else you say. The only practical way to accomplish that would be to process everything it hears, and continuously feed chunks into intent parsers. But then we'd have to figure out what to do with or to the intent handling process itself, because it currently operates on the assumption that *all* input is *always* either meant to be parsed or an accidental activation. It doesn't account for the possibility that you're constantly feeding it utterances *just to see if they're intents*.

This approach may also mess with the mechanisms that split follow-up utterances from new invocations of the same or similar intents.

And the privacy aspect is a great point from Gez:

> Then enter some special active mode that is very clear to anyone in the vicinity of the device that it is listening to everything being said.

...which can't be implemented on devices without screens.

**Comment by hanzala123** [comment]
@ChanceNCounter @krisgesling  So i have achieved what i was trying to achieve using this.
`    def initialize(self):
        self.add_event('recognizer_loop:audio_output_end',
                   self.handler_mycroft_skill_handler_complete)
    def handler_mycroft_skill_handler_complete(self, message):
        self.log.info('skill end')
        self.bus.emit(Message('mycroft.mic.listen'))`

So it is not listening always just after saying something it tries to find speech for once if it finds something it processes it and then repeats this until no there is not utterance and then goes back to wake word detection exactly like assistant. 

I thought it may interfere with other skills but it hasn't so far, even skills that use speak_dialog() with expect_response=True.  I will continue to test it and see if problems arise.

**Comment by JarbasAl** [comment]
this feature has been implemented in ovos, see https://github.com/OpenVoiceOS/ovos-core/pull/150

**Comment by forslund** [comment]
Closing Issue since we're archiving the repo
