### ISSUE TITLE
Discussion: Audioservice support for sound effects

### ISSUE THREAD

**Issue by forslund** [MycroftAI/mycroft-core#2965]
A "sound effect" audio service component could be useful.

Things like the alarm and timer skill uses sound effects to handle alarms and notifications. Adding such a service would reduce some of the code duplication in skills and make the user experience more coherent.

There is a value in keeping this outside the normal tracklist audioservice since we may want to overlap these. I.e pause the existing track list play the sound effect, resume playback. Or play the sound effect on top of the audio service.

Things that it could do:
- play sound effect (provided a file)
- play on repeat at an interval
- query if sfx is playing
- Provide a set of standard notification sounds for events, reminders, alarms to give a coherent user experience

~I think only one repeating sfx at a time should be handled, possibly a stack of the events so if a timer and an alarm is playing only one will sound will be output. The latest sfx will be the one playing. For example if the alarm is cancelled it would resume playing the timer.~

@ChanceNCounter suggested that if multiple repeating sfx's are running they should alternate which is a much better idea than the above in my opinion.

The query if sfx is playing can be good for the VK tests since it will make some of the wonkier tests in alarm / timer easier to implement.

**Comment by ChanceNCounter** [comment]
It could also alternate between repeating sounds, which could be useful if skills or their authors disagree with the user about relative urgency. Maybe you'd rather hear your timer, so you don't burn your dinner, whereas I'd rather hear an incoming call alert because people only voice call me when it's urgent.

*beep beep, beep beep* **ring ring** *beep beep, beep beep*

**Comment by forslund** [comment]
Updated the proposal with your suggestion.

**Comment by forslund** [comment]
A first draft can be seen here: https://github.com/forslund/mycroft-core/commit/b6cfd183353daeffd08ede05463677a917197337

**Comment by krisgesling** [comment]
Yeah nice one. 

It also feels like there may be different levels of importance for sound effects, off the top of my head:
- Intentionally interrupting notifications - eg alarms, timers, calls
- Essential Skill sound effects - eg game sound effects
- Non-essential interaction sounds - eg positive confirmation tone

Not sure exactly _how_ they should all be handled, but more to suggest that we may need a parameter for this level of importance so that we can handle them differently.

**Comment by forslund** [comment]
Good suggestion I'll add a way to provide the importance level to the api and make sure the they are stored in separate lists then maybe open a PR for more discussion if this is something the mycroft core team would like.

**Comment by krisgesling** [comment]
I think hold off doing too much just yet. We have a [Music Skills sprint](https://docs.google.com/document/d/1XCSdcszcuWhZsIHpkVrmHhFGHLdx7xqvd_BYELcXqTY/edit#heading=h.4h7ea78mwsol) coming up shortly that will have to include looking at the Common Play and Audiobackend Services so things will probably shift significantly through this.

**Comment by forslund** [comment]
Closing Issue since we're archiving the repo
