### ISSUE TITLE
Local configuration is sometimes ignored?

### ISSUE THREAD

**Issue by aatchison** [MycroftAI/mycroft-core#48]
When using an external microphone on units, I have used the ~/.mycroft/mycroft.ini configuration file to select another microphone. Here is an example:

`[speech_client]`
`device_index=1`

This seems to work fine, until after a reboot (or two,) and then Mycroft uses the default device (device_index=0) regardless of the configuration files contents or existence. This has happened to me twice now, but I don't have the exact steps to reproduce. I suspect that this might be causing other users to have trouble, especially those that have to take steps to specify certain channels and sample rates on their mics.

I think we may have some configuration file loading / parsing issues that are related to pulling down the remote configuration. 

Any ideas?

**Comment by ryanleesipes** [comment]
Remote configuration seems to overwrite local changes like this (possibly). @ethanaward this one falls to you as well.

**Comment by the7erm** [comment]
This might be a challenge because I'm not sure if pulse audio always loads the devices in the same order.  I remember hearing Chris on an episode of the Linux Action Show complaining about if he rebooted sometimes audio would go through HDMI sometimes the sound card.  @ethanaward when you're working on this one you might want to keep that in mind.  

I've intentionally disabled hdmi so even if I have a tv plugged in the audio won't route to my tv unless I explicitly tell it to.

So it may very well be using index 1, it's just the order changes.

**Comment by ryanleesipes** [comment]
Is this actually happening, anyone have any insight into what is going on here?

**Comment by jdorleans** [comment]
Does this still happening after #209 ?

**Comment by jdorleans** [comment]
Is this still happening after #209 ?

**Comment by aatchison** [comment]
I'm pretty sure that this has been solved. Thanks.
