### ISSUE TITLE
Add directories when setting up dev-env

### ISSUE THREAD

**Issue by kfezer** [MycroftAI/mycroft-core#509]
Add the /opt/mycroft/skills folders when setting up the dev environment when first installing Mycroft via git clone. 

Just one less step for devs.

**Comment by danielquinn** [comment]
This burned me, but it wouldn't have been a problem if the documentation had mentioned that I just need to run `./msm/msm default` after `./dev_setup.sh`

Why however are we using a hard-coded path of `/opt/mycroft/skills` for this though?  `./scripts/prepare-msm.sh` actually calls sudo create this directory.  Wouldn't it be better to keep everything inside the same dir?  Otherwise you could potentially end up overwriting people's stuff or just polluting their system with files & dirs they didn't know were going in there.

**Comment by forslund** [comment]
@danielquinn first of all I agree that the docs should be updated to reflect the /opt/mycroft directory and the dev setup script should probably be updated to do this automatically.

The idea behind the `/opt/mycroft` location is that the skills should live outside of the core installation since they will be installed, updated and removed without affecting the core installation of mycroft. To accommodate for all kinds of installations (packages, git clone, etc) the `/opt/mycroft` was selected. My assumption is that /opt was chosen since it's purpose is to house third party and binary software installs.

DISCLAIMER:
This is mainly assumptions based on discussions on slack a while ago. I was not privy to the original discussion leading up to this decision so I might very well be completely wrong.

**Comment by kfezer** [comment]
So I'm going to close this as it's now done by msm when mycroft is first run.

Where are the docs not showing the correct directory? I thought I corrected them all, but could have missed some.
