### ISSUE TITLE
APi de-cluttering

### ISSUE THREAD

**Issue by JarbasAI** [MycroftAI/mycroft-core#540]
at a certain point there will sure be lots of api keys, sometimes shared between skills (mashape key used in a bunch of my skills), having the same api in a section for each skill in .config is ugly,  we should have a section for apis only maybe?

in my build i added a self.APIconfig to base MycroftSkill , so i just do self.APIconfig.get(api), but not sure this is the best approach

**Comment by forslund** [comment]
Ok, closing this one. Feel free to reopen if you think it should remain.

**Comment by JarbasAl** [comment]
this served 2 purposes, ease of use which is no longer an issue because of skill settings and privacy reasons

i still like this approach for privacy reasons, keep your api keys in a single place and out of mycroft-home

it's less important now that we have skill settings, i will give it some more thought and open a PR if i come up with some cool solution

**Comment by devs-mycroft** [comment]
If it's a convention how to organize it may just be documentation needed. Since we're removing the Per skill config-blocks in 19.08 this might be something...

**Comment by forslund** [comment]
If it's a convention how to organize it may just be documentation needed. Since we're removing the Per skill config-blocks in 19.08 this might be something...
