### ISSUE TITLE
No terms of service or data collection policy

### ISSUE THREAD

**Issue by afranke** [MycroftAI/mycroft-core#719]
This is for home.mycroft.ai which is probably not part of mycroft-core but it is currently not possible to use mycroft-core without home.mycroft.ai and I couldn’t find the repository for home.mycroft.ai.

Mycroft requires one to create an account at home.mycroft.ai but the website doesn’t have any link to the terms of service or data collection policy.

**Comment by fermulator** [comment]
good ole closure w/out any information

**Comment by krisgesling** [comment]
Hey @fermulator - the two policies that are presented when you create an account are:
- http://mycroft.ai/embed-terms-of-use/
- http://mycroft.ai/embed-privacy-policy/

That covers what Mycroft will collect by default, but of course as it's open source you can use the code without accepting either because you aren't using our services.
