### ISSUE TITLE
Change config to YAML

### ISSUE THREAD

**Issue by MatthewScholefield** [MycroftAI/mycroft-core#846]
It looks like we are currently store `mycroft.conf` as a json where we process out comments. [YAML][site] supports comments directly (With `# Comment`) and also makes the config more readable.

[site]:http://yaml.org

**Comment by forslund** [comment]
Personally I have no experience with YAML but it seems quite popular.

For me the big advantage of using json is that it's very similar to python dicts and python developers, even inexperienced ones, will have no problem to understand how the items in the config-file maps to the configuration dictionary. (What looks like a python string is a python string, what looks like a dict is a dict etc.)

Another advantage might be that the data transfers are in json format (I think) and keeping the number of different formats down is a good thing I would say.

**Comment by MatthewScholefield** [comment]
I'm pretty sure YAML is just a nicer way to write JSON. In fact, valid JSON is also valid YAML. Just like you would do `json.load(json_file)`, you can do `yaml.load(yaml_file)`.

**Comment by forslund** [comment]
Oh, cool. Then it should be backwards compatible and less strict about the syntax! Would be great and would technically only require a couple of `:%s`

**Comment by MatthewScholefield** [comment]
Yep. And it will work fine with any remote configuration still being json.

**Comment by penrods** [comment]
I'm open to being swayed, but to me the JSON with comments achieves everything important.  And JSON is supported without adding another requirement.

**Comment by renekliment** [comment]
I have to say that YAML really makes a difference. JSON is a great format for machines, but not really for people. It is better than XML, but YAML is really that much more convenient. All those brackets, commas, quotation marks ... It's much easier, faster and comfortable to write YAML than JSON.

I have some experience with https://github.com/home-assistant/home-assistant ... if I had to write stuff in JSON instead of YAML, it would have been hell.

Please, make this happen.

**Comment by pavithranrao** [comment]
Can I pick this up? 

Could the team also review YAML vs PyHOCON (https://github.com/chimpler/pyhocon) since the pyhocon  supports comments with `#` and `//` and also has more features than `yaml`?

**Comment by forslund** [comment]
I think the discussion ended in that we'd like to keep the configuration as json. Since the users need to touch this config less and less it's better to keep it json.

I'm closing this issue, @penrods, @MatthewScholefield if I misremember feel free to reopen.

@pavithranrao I was not at all aware of PyHOCON, there are other places we're considering YAML (replacement for the requirements.txt/sh in skills) and it might be worth considering there.
