### ISSUE TITLE
No way to configure timezone for Mycroft 

### ISSUE THREAD

**Issue by nekoexmachina** [MycroftAI/mycroft-core#905]
I've Desktop installation from Git. Can not figure out how to configure Timezone. as I'm located in Czech Republic, its a PITA to hear Kansas time :-)

**Comment by ethanaward** [comment]
You can configure your timezone on our website, home.mycroft.ai, where you paired your device. Look in your account settings.

**Comment by arjenlentz** [comment]
You can also change it in the local configuration (mycroft.conf)

For instance, I did the following for my approximate location:

```
  // Location where the system resides
  // NOTE: Although this is set here, an Enclosure can override the value.
  //       For example a mycroft-core running in a car could use the GPS.
  // Override: REMOTE
  "location": {
    "city": {
      "code": "Brisbane",
      "name": "Brisbane",
      "state": {
        "code": "QLD",
        "name": "Queensland",
        "country": {
          "code": "AUS",
          "name": "Australia"
        }
      }
    },
    "coordinate": {
      "latitude": 27.3975,
      "longitude": 152.9594
    },
    "timezone": {
      "code": "Australia/Brisbane",
      "name": "Ausralian Eastern Standard Time",
      "dstOffset": 0,
      "offset": 36000000
    }
  },
```
 Note that the dstOffset and offset are in milliseconds.
So for each hour you need to add 3600, and multiply the total by 1000 (my 36000000 is because Brisbane is UTC+10 and Queensland doesn't do daylight savings so dstOffset is 0)

I think it's a tad crude to require it to be configured like this, I might look at doing a patch that at least documents how-to, but preferably sorts it out to something more human-readable.

**Comment by forslund** [comment]
@nekoexmachina Since there has gone six months with out activity here I'm assuming you're happy with the answers you received. Closing the issue.
