### ISSUE TITLE
How do I get started with mycroft?

### ISSUE THREAD

**Issue by santhisenan** [MycroftAI/mycroft-core#930]

**Comment by forslund** [comment]
Hi,

This will be very general since I don't know your background or what OS you are used to. If you provide more details like that I can probably give you a couple additional advices.

First! There's a friendly community at mycroftai.slack.com and a friendly forum at https://community.mycroft.ai/ to help you.

There are a couple of ways to set up Mycroft. 

1. [ Install from this git repository](https://docs.mycroft.ai/installing.and.running/installation/git.clone.install). The exact procedure depends a bit on the OS you are running but this is the definite choice if you want to contribute code. 
2. If you have a Raspberry Pi, Mic and speaker you can use the [Picroft image](https://docs.mycroft.ai/installing.and.running/installation/raspberry.pi)
3. [Buy](https://mycroft-ai.backerkit.com/hosted_preorders) the Mark-1 unit. Not sure about the current delivery times though.

**Comment by forslund** [comment]
An update to this the new mattermost chat replaces the slack mentioned earlier. Sign up here: https://chat.mycroft.ai/signup_email

I'm closing this issue, join us in the chat or forum or reopen this issue if you have more questions!
