### ISSUE TITLE
Provide Intent Tests for New Skills

### ISSUE THREAD

**Issue by ryanleesipes** [MycroftAI/mycroft-core#94]
Need to provide tests for new skills.

**Comment by ChristopherRios7** [comment]
I am on it!

**Comment by ethanaward** [comment]
This should also be largely fixed by #120. I added intent tests for almost all of the skills that didn't have them, with the exception of those that seemed like a special case, such as the `stop` and `cerberus-config` skills. One of the intents for the `desktop-launcher` is also not being hit, since it gets its list of Application vocab from what's currently installed on the system, so any test would need to know what's installed on the Travis test servers in order for those tests to pass.

**Comment by ryanleesipes** [comment]
@ethanaward please provide feedback on whether or not we should close this.

**Comment by ethanaward** [comment]
I think we should, yeah. All of the current skills have intent tests. We can open up a separate issue for the `desktop-client` test that I was having trouble with, and possible ask the creator of the skill about it. We should make sure that new skills have intent tests, however.
