### ISSUE TITLE
After setup Mycroft fails at startup when power was disconnected

### ISSUE THREAD

**Issue by kodaren** [MycroftAI/mycroft-core#968]
Hi,

I just got and setup Mycroft and it was working properly, i.e. I asked questions and got answers. However, I then disconnected the power and now when I startup the eyes keep spinning. Only tests can be run (successfully) when pressing the menu button. I haven't tried SSH yet. When I connect it to HDMI it seems that the file system has failed. There is no way to restore it. I tried the reset in the menu options, but the eyes still keep spinning forever. Maybe you should add a test and fix for filesystem corruption?

Best regards,

Jimmy Karlsson

**Comment by forslund** [comment]
Hej Jimmy!

That sounds like a really bad situation, can you recover using a keyboard?

is it the old `press Enter for Maintanance (or ctrl + D) to continue` or is it something else?

**Comment by kodaren** [comment]
Hi,
It justs stops during boot and I get a Kernel Panic - Unable to mount VFS etc. So sounds like a corrupt file system.

/Jimmy

**Comment by forslund** [comment]
Sorry for grave digging this Issue, I seem to have missed your response. Did you get a new image for your system. If not you can get the latest from https://mycroft.ai/to/mark-1-image and dust off your old unit :)

Since this is an almost 2 years since it was opened I'm going to close it.

Ha det bra
- Åke
