### ISSUE TITLE
Hot word recognizer

### ISSUE THREAD

**Issue by JarbasAI** [MycroftAI/mycroft-core#986]
Listening for common words could be usefull, yes no stop come to mind

proposal:
- add any number of hot words to config
- hot word can be any engine (snowboy/pocketsphinx)
- hot word can trigger listening or not
- hot word can play a sound or not
- hot word can be treated as full utterance or not

https://github.com/MycroftAI/mycroft-core/compare/dev...JarbasAI:patch-20

a WakeWordFactory should eventually be made

youtube video demo: https://www.youtube.com/watch?v=GIkBh0VFmbc&feature=youtu.be

**Comment by forslund** [comment]
Very cool, sounds very much like this todo task: https://github.com/MycroftAI/mycroft-core/wiki/TASK-WuW_SimpleCommands

I think snowboy integration is still a no-go because of licenses but if users want to install it, there is no issue whatsoever =)

The I think the architecture changes by @MatthewScholefield was intended to make other hot-word detectors easier to integrate

**Comment by JarbasAI** [comment]
should i make a PR using pocketsphinx only? havent really tested with pocketsphinx, but should be functional

**Comment by MatthewScholefield** [comment]
@JarbasAI Yeah, that sounds like a great idea!

**Comment by arjenlentz** [comment]
pocketsphinx is happy to listen for a list of keyphrases already, so this sounds like a fine plan to also support in Mycroft.

**Comment by JarbasAI** [comment]
#1233

**Comment by krisgesling** [comment]
https://github.com/castorini/howl/ seems like a good candidate for this

**Comment by forslund** [comment]
Closing Issue since we're archiving the repo
